//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for addressBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="addressBase">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AddressPeriod" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}dateRangeOpen"/>
 *         &lt;element name="PreAddressLine" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}string100" minOccurs="0"/>
 *         &lt;element name="Line1" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}string100"/>
 *         &lt;element name="Line2" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}string100" minOccurs="0"/>
 *         &lt;element name="City" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}string50"/>
 *         &lt;element name="County" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}string50" minOccurs="0"/>
 *         &lt;element name="State" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}state"/>
 *         &lt;element name="ZIPCode" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}zIPCode" minOccurs="0"/>
 *         &lt;element name="Country" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}string50" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addressBase", propOrder = {
    "addressPeriod",
    "preAddressLine",
    "line1",
    "line2",
    "city",
    "county",
    "state",
    "zipCode",
    "country"
})
@XmlSeeAlso({
    PersonAddressBase.class
})
public class AddressBase {

    @XmlElement(name = "AddressPeriod", required = true)
    protected DateRangeOpen addressPeriod;
    @XmlElement(name = "PreAddressLine")
    protected String100 preAddressLine;
    @XmlElement(name = "Line1", required = true)
    protected String100 line1;
    @XmlElement(name = "Line2")
    protected String100 line2;
    @XmlElement(name = "City", required = true)
    protected String50 city;
    @XmlElement(name = "County")
    protected String50 county;
    @XmlElement(name = "State", required = true)
    protected State state;
    @XmlElement(name = "ZIPCode")
    protected ZIPCode zipCode;
    @XmlElement(name = "Country")
    protected String50 country;

    /**
     * Gets the value of the addressPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link DateRangeOpen }
     *     
     */
    public DateRangeOpen getAddressPeriod() {
        return addressPeriod;
    }

    /**
     * Sets the value of the addressPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRangeOpen }
     *     
     */
    public void setAddressPeriod(DateRangeOpen value) {
        this.addressPeriod = value;
    }

    /**
     * Gets the value of the preAddressLine property.
     * 
     * @return
     *     possible object is
     *     {@link String100 }
     *     
     */
    public String100 getPreAddressLine() {
        return preAddressLine;
    }

    /**
     * Sets the value of the preAddressLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String100 }
     *     
     */
    public void setPreAddressLine(String100 value) {
        this.preAddressLine = value;
    }

    /**
     * Gets the value of the line1 property.
     * 
     * @return
     *     possible object is
     *     {@link String100 }
     *     
     */
    public String100 getLine1() {
        return line1;
    }

    /**
     * Sets the value of the line1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String100 }
     *     
     */
    public void setLine1(String100 value) {
        this.line1 = value;
    }

    /**
     * Gets the value of the line2 property.
     * 
     * @return
     *     possible object is
     *     {@link String100 }
     *     
     */
    public String100 getLine2() {
        return line2;
    }

    /**
     * Sets the value of the line2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String100 }
     *     
     */
    public void setLine2(String100 value) {
        this.line2 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String50 }
     *     
     */
    public String50 getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String50 }
     *     
     */
    public void setCity(String50 value) {
        this.city = value;
    }

    /**
     * Gets the value of the county property.
     * 
     * @return
     *     possible object is
     *     {@link String50 }
     *     
     */
    public String50 getCounty() {
        return county;
    }

    /**
     * Sets the value of the county property.
     * 
     * @param value
     *     allowed object is
     *     {@link String50 }
     *     
     */
    public void setCounty(String50 value) {
        this.county = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link State }
     *     
     */
    public State getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link State }
     *     
     */
    public void setState(State value) {
        this.state = value;
    }

    /**
     * Gets the value of the zipCode property.
     * 
     * @return
     *     possible object is
     *     {@link ZIPCode }
     *     
     */
    public ZIPCode getZIPCode() {
        return zipCode;
    }

    /**
     * Sets the value of the zipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZIPCode }
     *     
     */
    public void setZIPCode(ZIPCode value) {
        this.zipCode = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String50 }
     *     
     */
    public String50 getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String50 }
     *     
     */
    public void setCountry(String50 value) {
        this.country = value;
    }

}
