//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for assignment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="assignment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AssignmentID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}iDIndex"/>
 *         &lt;element name="PersonID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}id"/>
 *         &lt;element name="HouseholdID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}id" minOccurs="0"/>
 *         &lt;element name="AssignmentPeriod" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}dateRangeCapped" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "assignment", propOrder = {
    "assignmentID",
    "personID",
    "householdID",
    "assignmentPeriod"
})
public class Assignment {

    @XmlElement(name = "AssignmentID", required = true)
    protected IDIndex assignmentID;
    @XmlElement(name = "PersonID", required = true)
    protected Id personID;
    @XmlElement(name = "HouseholdID")
    protected Id householdID;
    @XmlElement(name = "AssignmentPeriod")
    protected List<DateRangeCapped> assignmentPeriod;

    /**
     * Gets the value of the assignmentID property.
     * 
     * @return
     *     possible object is
     *     {@link IDIndex }
     *     
     */
    public IDIndex getAssignmentID() {
        return assignmentID;
    }

    /**
     * Sets the value of the assignmentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDIndex }
     *     
     */
    public void setAssignmentID(IDIndex value) {
        this.assignmentID = value;
    }

    /**
     * Gets the value of the personID property.
     * 
     * @return
     *     possible object is
     *     {@link Id }
     *     
     */
    public Id getPersonID() {
        return personID;
    }

    /**
     * Sets the value of the personID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id }
     *     
     */
    public void setPersonID(Id value) {
        this.personID = value;
    }

    /**
     * Gets the value of the householdID property.
     * 
     * @return
     *     possible object is
     *     {@link Id }
     *     
     */
    public Id getHouseholdID() {
        return householdID;
    }

    /**
     * Sets the value of the householdID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id }
     *     
     */
    public void setHouseholdID(Id value) {
        this.householdID = value;
    }

    /**
     * Gets the value of the assignmentPeriod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assignmentPeriod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssignmentPeriod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateRangeCapped }
     * 
     * 
     */
    public List<DateRangeCapped> getAssignmentPeriod() {
        if (assignmentPeriod == null) {
            assignmentPeriod = new ArrayList<DateRangeCapped>();
        }
        return this.assignmentPeriod;
    }

}
