//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for barrier complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="barrier">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BarrierID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}iDIndex"/>
 *         &lt;element name="BarrierCode" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}barrierCode" minOccurs="0"/>
 *         &lt;element name="BarrierOther" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}string50" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "barrier", propOrder = {
    "barrierID",
    "barrierCode",
    "barrierOther"
})
public class Barrier {

    @XmlElement(name = "BarrierID", required = true)
    protected IDIndex barrierID;
    @XmlElement(name = "BarrierCode")
    protected BarrierCode barrierCode;
    @XmlElement(name = "BarrierOther")
    protected String50 barrierOther;

    /**
     * Gets the value of the barrierID property.
     * 
     * @return
     *     possible object is
     *     {@link IDIndex }
     *     
     */
    public IDIndex getBarrierID() {
        return barrierID;
    }

    /**
     * Sets the value of the barrierID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDIndex }
     *     
     */
    public void setBarrierID(IDIndex value) {
        this.barrierID = value;
    }

    /**
     * Gets the value of the barrierCode property.
     * 
     * @return
     *     possible object is
     *     {@link BarrierCode }
     *     
     */
    public BarrierCode getBarrierCode() {
        return barrierCode;
    }

    /**
     * Sets the value of the barrierCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BarrierCode }
     *     
     */
    public void setBarrierCode(BarrierCode value) {
        this.barrierCode = value;
    }

    /**
     * Gets the value of the barrierOther property.
     * 
     * @return
     *     possible object is
     *     {@link String50 }
     *     
     */
    public String50 getBarrierOther() {
        return barrierOther;
    }

    /**
     * Sets the value of the barrierOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String50 }
     *     
     */
    public void setBarrierOther(String50 value) {
        this.barrierOther = value;
    }

}
