//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for bedCountBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bedCountBase">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>nonNegativeInteger">
 *       &lt;attGroup ref="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}bedAndUnitInfo"/>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bedCountBase", propOrder = {
    "value"
})
public class BedCountBase {

    @XmlValue
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger value;
    @XmlAttribute(name = "bedAvailability", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd")
    protected Long bedAvailability;
    @XmlAttribute(name = "bedStatus", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd")
    protected Long bedStatus;
    @XmlAttribute(name = "bedType", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd")
    protected Long bedType;
    @XmlAttribute(name = "bedIndividualFamilyType", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd")
    protected Long bedIndividualFamilyType;
    @XmlAttribute(name = "chronicHomelessBed", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd")
    protected Long chronicHomelessBed;
    @XmlAttribute(name = "domesticViolenceShelterBed", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd")
    protected Long domesticViolenceShelterBed;
    @XmlAttribute(name = "householdType", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd")
    protected Long householdType;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setValue(BigInteger value) {
        this.value = value;
    }

    /**
     * Gets the value of the bedAvailability property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBedAvailability() {
        return bedAvailability;
    }

    /**
     * Sets the value of the bedAvailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBedAvailability(Long value) {
        this.bedAvailability = value;
    }

    /**
     * Gets the value of the bedStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBedStatus() {
        return bedStatus;
    }

    /**
     * Sets the value of the bedStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBedStatus(Long value) {
        this.bedStatus = value;
    }

    /**
     * Gets the value of the bedType property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBedType() {
        return bedType;
    }

    /**
     * Sets the value of the bedType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBedType(Long value) {
        this.bedType = value;
    }

    /**
     * Gets the value of the bedIndividualFamilyType property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBedIndividualFamilyType() {
        return bedIndividualFamilyType;
    }

    /**
     * Sets the value of the bedIndividualFamilyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBedIndividualFamilyType(Long value) {
        this.bedIndividualFamilyType = value;
    }

    /**
     * Gets the value of the chronicHomelessBed property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getChronicHomelessBed() {
        return chronicHomelessBed;
    }

    /**
     * Sets the value of the chronicHomelessBed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setChronicHomelessBed(Long value) {
        this.chronicHomelessBed = value;
    }

    /**
     * Gets the value of the domesticViolenceShelterBed property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDomesticViolenceShelterBed() {
        return domesticViolenceShelterBed;
    }

    /**
     * Sets the value of the domesticViolenceShelterBed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDomesticViolenceShelterBed(Long value) {
        this.domesticViolenceShelterBed = value;
    }

    /**
     * Gets the value of the householdType property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getHouseholdType() {
        return householdType;
    }

    /**
     * Sets the value of the householdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHouseholdType(Long value) {
        this.householdType = value;
    }

}
