//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for childEnrollmentStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="childEnrollmentStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ChildEnrollmentStatusID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}iDIndex"/>
 *         &lt;element name="ChildCurrentlyEnrolledInSchool" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}fourValDKRefused" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;group ref="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}childEnrolledYes"/>
 *           &lt;group ref="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}childEnrolledNo"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "childEnrollmentStatus", propOrder = {
    "childEnrollmentStatusID",
    "childCurrentlyEnrolledInSchool",
    "childSchoolName",
    "childMcKinneyVentoLiaison",
    "childSchoolType",
    "childEnrollmentBarrier",
    "childSchoolLastEnrolledDate"
})
public class ChildEnrollmentStatus {

    @XmlElement(name = "ChildEnrollmentStatusID", required = true)
    protected IDIndex childEnrollmentStatusID;
    @XmlElement(name = "ChildCurrentlyEnrolledInSchool")
    protected FourValDKRefused childCurrentlyEnrolledInSchool;
    @XmlElement(name = "ChildSchoolName")
    protected String50 childSchoolName;
    @XmlElement(name = "ChildMcKinneyVentoLiaison")
    protected FourValDKRefused childMcKinneyVentoLiaison;
    @XmlElement(name = "ChildSchoolType")
    protected FourValDKRefused2 childSchoolType;
    @XmlElement(name = "ChildEnrollmentBarrier")
    protected List<Barrier> childEnrollmentBarrier;
    @XmlElement(name = "ChildSchoolLastEnrolledDate")
    protected Date childSchoolLastEnrolledDate;

    /**
     * Gets the value of the childEnrollmentStatusID property.
     * 
     * @return
     *     possible object is
     *     {@link IDIndex }
     *     
     */
    public IDIndex getChildEnrollmentStatusID() {
        return childEnrollmentStatusID;
    }

    /**
     * Sets the value of the childEnrollmentStatusID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDIndex }
     *     
     */
    public void setChildEnrollmentStatusID(IDIndex value) {
        this.childEnrollmentStatusID = value;
    }

    /**
     * Gets the value of the childCurrentlyEnrolledInSchool property.
     * 
     * @return
     *     possible object is
     *     {@link FourValDKRefused }
     *     
     */
    public FourValDKRefused getChildCurrentlyEnrolledInSchool() {
        return childCurrentlyEnrolledInSchool;
    }

    /**
     * Sets the value of the childCurrentlyEnrolledInSchool property.
     * 
     * @param value
     *     allowed object is
     *     {@link FourValDKRefused }
     *     
     */
    public void setChildCurrentlyEnrolledInSchool(FourValDKRefused value) {
        this.childCurrentlyEnrolledInSchool = value;
    }

    /**
     * Gets the value of the childSchoolName property.
     * 
     * @return
     *     possible object is
     *     {@link String50 }
     *     
     */
    public String50 getChildSchoolName() {
        return childSchoolName;
    }

    /**
     * Sets the value of the childSchoolName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String50 }
     *     
     */
    public void setChildSchoolName(String50 value) {
        this.childSchoolName = value;
    }

    /**
     * Gets the value of the childMcKinneyVentoLiaison property.
     * 
     * @return
     *     possible object is
     *     {@link FourValDKRefused }
     *     
     */
    public FourValDKRefused getChildMcKinneyVentoLiaison() {
        return childMcKinneyVentoLiaison;
    }

    /**
     * Sets the value of the childMcKinneyVentoLiaison property.
     * 
     * @param value
     *     allowed object is
     *     {@link FourValDKRefused }
     *     
     */
    public void setChildMcKinneyVentoLiaison(FourValDKRefused value) {
        this.childMcKinneyVentoLiaison = value;
    }

    /**
     * Gets the value of the childSchoolType property.
     * 
     * @return
     *     possible object is
     *     {@link FourValDKRefused2 }
     *     
     */
    public FourValDKRefused2 getChildSchoolType() {
        return childSchoolType;
    }

    /**
     * Sets the value of the childSchoolType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FourValDKRefused2 }
     *     
     */
    public void setChildSchoolType(FourValDKRefused2 value) {
        this.childSchoolType = value;
    }

    /**
     * Gets the value of the childEnrollmentBarrier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the childEnrollmentBarrier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChildEnrollmentBarrier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Barrier }
     * 
     * 
     */
    public List<Barrier> getChildEnrollmentBarrier() {
        if (childEnrollmentBarrier == null) {
            childEnrollmentBarrier = new ArrayList<Barrier>();
        }
        return this.childEnrollmentBarrier;
    }

    /**
     * Gets the value of the childSchoolLastEnrolledDate property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getChildSchoolLastEnrolledDate() {
        return childSchoolLastEnrolledDate;
    }

    /**
     * Sets the value of the childSchoolLastEnrolledDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setChildSchoolLastEnrolledDate(Date value) {
        this.childSchoolLastEnrolledDate = value;
    }

}
