//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for contactLocation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="contactLocation">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.hmis.info/schema/3_0/HUD_HMIS.xsd>threeValBase">
 *       &lt;attribute name="dataCollectionStage" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}fourValBase" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "contactLocation", propOrder = {
    "value"
})
public class ContactLocation {

    @XmlValue
    protected long value;
    @XmlAttribute(name = "dataCollectionStage", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd")
    protected Long dataCollectionStage;

    /**
     * 
     * 				threeVal: Applicable to:				
     * 				Bed Availability
     *     				1 = Year-round
     *     				2 = Seasonal
     *     				3 = Overflow
     * 				Bed Type
     *     				1 = Facility-based
     *     				2 = Voucher
     *     				3 = Other
     *     			Bed Status
     *     				1 = Current - Been in use for over a year  (Current:  inventory start date before applicable date - 1 year)
     *     				2 = New.  Less than a year old (New: Inventory start date > applicable date - 1 year) 
     *     				3 = Under Development .  Under Dev:  Inventory start date > applicable date )
     * 				Export Hashing
     *     				1 = No
     *     				2 = Yes
     *     				3 = Mixed
     * 				Location of Contact 
     *     				1 = Place not meant for habitation (e.g. vehicle, abandoned building, bus/train/subway 
     *     				station/airport or anywhere outside that is not a Homeless
     *     				Connect-type event)
     *     				2 = Service setting, non-residential (e.g. Homeless Connect-type event, drop in	center, 
     *     				day services center, soup kitchen, etc.)
     *     				3 = Service setting, residential (e.g. emergency, transitional or permanent housing;
     *     				treatment facility, including health, mental health, or substance abuse clinic or
     *     				hospital; jail, prison, or juvenile detention facility; family or friend’s room,
     *     				apartment, condo, or house; foster care or group home)
     * 				Method for Tracking Residential Program HMIS Utilization
     *     				0 = Program Entry and Exit Date Comparison
     *     				1 = Bed Management Model
     *     				2 = Service Transaction Model
     * 				Need Status
     *     				1 = Logged
     *     				2 = Lapsed
     *     				3 = Met
     *     			PIT Household Type
     *     				1 = Households without children
     *     				2 = Households with at least one adult and one child
     *     				3 = Households with only children
     * 				Program Site Configuration Type
     *     				1 = Single site, single building
     *     				2 = Single site, multiple buildings
     *     				3 = Multiple sites
     * 				Site Type/SiteService Type
     *     				1 = Non-residential: services only.
     *     				2 = Residential: special needs and non-special needs.
     *     				3 = Residential: special needs only.
     * 			
     * 
     */
    public long getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(long value) {
        this.value = value;
    }

    /**
     * Gets the value of the dataCollectionStage property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDataCollectionStage() {
        return dataCollectionStage;
    }

    /**
     * Sets the value of the dataCollectionStage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDataCollectionStage(Long value) {
        this.dataCollectionStage = value;
    }

}
