//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for contactMade complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="contactMade">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ContactID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}iDIndex"/>
 *         &lt;element name="ContactDate" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}contactDate"/>
 *         &lt;element name="ContactLocation" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}contactLocation"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "contactMade", propOrder = {
    "contactID",
    "contactDate",
    "contactLocation"
})
public class ContactMade {

    @XmlElement(name = "ContactID", required = true)
    protected IDIndex contactID;
    @XmlElement(name = "ContactDate", required = true)
    protected ContactDate contactDate;
    @XmlElement(name = "ContactLocation", required = true)
    protected ContactLocation contactLocation;

    /**
     * Gets the value of the contactID property.
     * 
     * @return
     *     possible object is
     *     {@link IDIndex }
     *     
     */
    public IDIndex getContactID() {
        return contactID;
    }

    /**
     * Sets the value of the contactID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDIndex }
     *     
     */
    public void setContactID(IDIndex value) {
        this.contactID = value;
    }

    /**
     * Gets the value of the contactDate property.
     * 
     * @return
     *     possible object is
     *     {@link ContactDate }
     *     
     */
    public ContactDate getContactDate() {
        return contactDate;
    }

    /**
     * Sets the value of the contactDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactDate }
     *     
     */
    public void setContactDate(ContactDate value) {
        this.contactDate = value;
    }

    /**
     * Gets the value of the contactLocation property.
     * 
     * @return
     *     possible object is
     *     {@link ContactLocation }
     *     
     */
    public ContactLocation getContactLocation() {
        return contactLocation;
    }

    /**
     * Sets the value of the contactLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactLocation }
     *     
     */
    public void setContactLocation(ContactLocation value) {
        this.contactLocation = value;
    }

}
