//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for degree complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="degree">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DegreeID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}iDIndex"/>
 *         &lt;element name="DegreeCode" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}degreeCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DegreeOther" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}string50" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "degree", propOrder = {
    "degreeID",
    "degreeCode",
    "degreeOther"
})
public class Degree {

    @XmlElement(name = "DegreeID", required = true)
    protected IDIndex degreeID;
    @XmlElement(name = "DegreeCode")
    protected List<DegreeCode> degreeCode;
    @XmlElement(name = "DegreeOther")
    protected String50 degreeOther;

    /**
     * Gets the value of the degreeID property.
     * 
     * @return
     *     possible object is
     *     {@link IDIndex }
     *     
     */
    public IDIndex getDegreeID() {
        return degreeID;
    }

    /**
     * Sets the value of the degreeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDIndex }
     *     
     */
    public void setDegreeID(IDIndex value) {
        this.degreeID = value;
    }

    /**
     * Gets the value of the degreeCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the degreeCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDegreeCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DegreeCode }
     * 
     * 
     */
    public List<DegreeCode> getDegreeCode() {
        if (degreeCode == null) {
            degreeCode = new ArrayList<DegreeCode>();
        }
        return this.degreeCode;
    }

    /**
     * Gets the value of the degreeOther property.
     * 
     * @return
     *     possible object is
     *     {@link String50 }
     *     
     */
    public String50 getDegreeOther() {
        return degreeOther;
    }

    /**
     * Sets the value of the degreeOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String50 }
     *     
     */
    public void setDegreeOther(String50 value) {
        this.degreeOther = value;
    }

}
