//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for destinationCode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="destinationCode">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.hmis.info/schema/3_0/HUD_HMIS.xsd>destinationBase">
 *       &lt;attGroup ref="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}dateStampGroup"/>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "destinationCode", propOrder = {
    "value"
})
public class DestinationCode {

    @XmlValue
    protected long value;
    @XmlAttribute(name = "dateCollected", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateCollected;
    @XmlAttribute(name = "dateEffective", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateEffective;
    @XmlAttribute(name = "dataCollectionStage", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd")
    protected Long dataCollectionStage;

    /**
     *    
     * 				Destination Type
     * 				1 = Emergency shelter, including hotel or motel paid for with emergency shelter voucher*
     * 				2 = Transitional housing for homeless persons (including homeless youth)*
     * 				3 = Permanent supportive housing for formerly homeless persons (such as SHP, S+C, or SRO Mod Rehab)
     * 				4 = Psychiatric hospital or other psychiatric facility
     * 				5 = Substance abuse treatment facility or detox center
     * 				6 = Hospital (non-psychiatric)
     * 				7 = Jail, prison or juvenile detention facility
     * 				10 = Rental by client, no ongoing housing subsidy
     * 				11 = Owned by client, no ongoing housing subsidy
     * 				12 = Staying or living with family, temporary tenure (e.g., room, apartment or house)
     * 				13 = Staying or living with friends, temporary tenure (.e.,g, room apartment or house;)
     * 				14 = Hotel or motel paid for without emergency shelter voucher
     * 				15 = Foster care home or foster care group home
     * 				16 = Place not meant for habitation (e.g., a vehicle, an abandoned building, bus/train/subway station/airport or anywhere outside)
     * 				17 = Other
     * 				18 = Safe Haven
     * 				19 = Rental by client, VASH Subsidy
     * 				20 = Rental by client, other (non-VASH) ongoing housing subsidy				
     * 				21 = Owned by client, with ongoing housing subsidy:
     * 				22 = Staying or living with family, permanent tenure
     * 				23 = Staying or living with friends, permanent tenure
     * 				24 = Deceased
     * 				8 = Don’t Know
     * 				9 = Refused
     * 			
     * 
     */
    public long getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(long value) {
        this.value = value;
    }

    /**
     * Gets the value of the dateCollected property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateCollected() {
        return dateCollected;
    }

    /**
     * Sets the value of the dateCollected property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateCollected(XMLGregorianCalendar value) {
        this.dateCollected = value;
    }

    /**
     * Gets the value of the dateEffective property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateEffective() {
        return dateEffective;
    }

    /**
     * Sets the value of the dateEffective property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateEffective(XMLGregorianCalendar value) {
        this.dateEffective = value;
    }

    /**
     * Gets the value of the dataCollectionStage property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDataCollectionStage() {
        return dataCollectionStage;
    }

    /**
     * Sets the value of the dataCollectionStage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDataCollectionStage(Long value) {
        this.dataCollectionStage = value;
    }

}
