//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for developmentalDisability complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="developmentalDisability">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HasDevelopmentalDisability" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}fourValDKRefused"/>
 *         &lt;element name="ReceiveDevelopmentalDisabilityServicesTreatment" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}fourValDKRefused" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "developmentalDisability", propOrder = {
    "hasDevelopmentalDisability",
    "receiveDevelopmentalDisabilityServicesTreatment"
})
public class DevelopmentalDisability {

    @XmlElement(name = "HasDevelopmentalDisability", required = true)
    protected FourValDKRefused hasDevelopmentalDisability;
    @XmlElement(name = "ReceiveDevelopmentalDisabilityServicesTreatment")
    protected FourValDKRefused receiveDevelopmentalDisabilityServicesTreatment;

    /**
     * Gets the value of the hasDevelopmentalDisability property.
     * 
     * @return
     *     possible object is
     *     {@link FourValDKRefused }
     *     
     */
    public FourValDKRefused getHasDevelopmentalDisability() {
        return hasDevelopmentalDisability;
    }

    /**
     * Sets the value of the hasDevelopmentalDisability property.
     * 
     * @param value
     *     allowed object is
     *     {@link FourValDKRefused }
     *     
     */
    public void setHasDevelopmentalDisability(FourValDKRefused value) {
        this.hasDevelopmentalDisability = value;
    }

    /**
     * Gets the value of the receiveDevelopmentalDisabilityServicesTreatment property.
     * 
     * @return
     *     possible object is
     *     {@link FourValDKRefused }
     *     
     */
    public FourValDKRefused getReceiveDevelopmentalDisabilityServicesTreatment() {
        return receiveDevelopmentalDisabilityServicesTreatment;
    }

    /**
     * Sets the value of the receiveDevelopmentalDisabilityServicesTreatment property.
     * 
     * @param value
     *     allowed object is
     *     {@link FourValDKRefused }
     *     
     */
    public void setReceiveDevelopmentalDisabilityServicesTreatment(FourValDKRefused value) {
        this.receiveDevelopmentalDisabilityServicesTreatment = value;
    }

}
