//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for employment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="employment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EmploymentID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}iDIndex"/>
 *         &lt;element name="CurrentlyEmployed" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}fourValDKRefused" minOccurs="0"/>
 *         &lt;element name="HoursWorkedLastWeek" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="EmploymentTenure" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}fiveValDKRefused" minOccurs="0"/>
 *         &lt;element name="LookingForWork" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}fourValDKRefused" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "employment", propOrder = {
    "employmentID",
    "currentlyEmployed",
    "hoursWorkedLastWeek",
    "employmentTenure",
    "lookingForWork"
})
public class Employment {

    @XmlElement(name = "EmploymentID", required = true)
    protected IDIndex employmentID;
    @XmlElement(name = "CurrentlyEmployed")
    protected FourValDKRefused currentlyEmployed;
    @XmlElement(name = "HoursWorkedLastWeek")
    protected NonNegativeInteger hoursWorkedLastWeek;
    @XmlElement(name = "EmploymentTenure")
    protected FiveValDKRefused employmentTenure;
    @XmlElement(name = "LookingForWork")
    protected FourValDKRefused lookingForWork;

    /**
     * Gets the value of the employmentID property.
     * 
     * @return
     *     possible object is
     *     {@link IDIndex }
     *     
     */
    public IDIndex getEmploymentID() {
        return employmentID;
    }

    /**
     * Sets the value of the employmentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDIndex }
     *     
     */
    public void setEmploymentID(IDIndex value) {
        this.employmentID = value;
    }

    /**
     * Gets the value of the currentlyEmployed property.
     * 
     * @return
     *     possible object is
     *     {@link FourValDKRefused }
     *     
     */
    public FourValDKRefused getCurrentlyEmployed() {
        return currentlyEmployed;
    }

    /**
     * Sets the value of the currentlyEmployed property.
     * 
     * @param value
     *     allowed object is
     *     {@link FourValDKRefused }
     *     
     */
    public void setCurrentlyEmployed(FourValDKRefused value) {
        this.currentlyEmployed = value;
    }

    /**
     * Gets the value of the hoursWorkedLastWeek property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeInteger }
     *     
     */
    public NonNegativeInteger getHoursWorkedLastWeek() {
        return hoursWorkedLastWeek;
    }

    /**
     * Sets the value of the hoursWorkedLastWeek property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeInteger }
     *     
     */
    public void setHoursWorkedLastWeek(NonNegativeInteger value) {
        this.hoursWorkedLastWeek = value;
    }

    /**
     * Gets the value of the employmentTenure property.
     * 
     * @return
     *     possible object is
     *     {@link FiveValDKRefused }
     *     
     */
    public FiveValDKRefused getEmploymentTenure() {
        return employmentTenure;
    }

    /**
     * Sets the value of the employmentTenure property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiveValDKRefused }
     *     
     */
    public void setEmploymentTenure(FiveValDKRefused value) {
        this.employmentTenure = value;
    }

    /**
     * Gets the value of the lookingForWork property.
     * 
     * @return
     *     possible object is
     *     {@link FourValDKRefused }
     *     
     */
    public FourValDKRefused getLookingForWork() {
        return lookingForWork;
    }

    /**
     * Sets the value of the lookingForWork property.
     * 
     * @param value
     *     allowed object is
     *     {@link FourValDKRefused }
     *     
     */
    public void setLookingForWork(FourValDKRefused value) {
        this.lookingForWork = value;
    }

}
