//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for export complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="export">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ExportID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}iDIndex"/>
 *         &lt;element name="ExportDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="ExportPeriod" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}dateRangeCapped" minOccurs="0"/>
 *         &lt;element name="Agency" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}agency" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Household" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}household" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Person" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}person" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Service" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}service" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Site" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}site" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SiteService" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}siteService" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "export", propOrder = {
    "exportID",
    "exportDate",
    "exportPeriod",
    "agency",
    "household",
    "person",
    "service",
    "site",
    "siteService"
})
public class Export {

    @XmlElement(name = "ExportID", required = true)
    protected IDIndex exportID;
    @XmlElement(name = "ExportDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar exportDate;
    @XmlElement(name = "ExportPeriod")
    protected DateRangeCapped exportPeriod;
    @XmlElement(name = "Agency")
    protected List<Agency> agency;
    @XmlElement(name = "Household")
    protected List<Household> household;
    @XmlElement(name = "Person")
    protected List<Person> person;
    @XmlElement(name = "Service")
    protected List<Service> service;
    @XmlElement(name = "Site")
    protected List<Site> site;
    @XmlElement(name = "SiteService")
    protected List<SiteService> siteService;

    /**
     * Gets the value of the exportID property.
     * 
     * @return
     *     possible object is
     *     {@link IDIndex }
     *     
     */
    public IDIndex getExportID() {
        return exportID;
    }

    /**
     * Sets the value of the exportID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDIndex }
     *     
     */
    public void setExportID(IDIndex value) {
        this.exportID = value;
    }

    /**
     * Gets the value of the exportDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExportDate() {
        return exportDate;
    }

    /**
     * Sets the value of the exportDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExportDate(XMLGregorianCalendar value) {
        this.exportDate = value;
    }

    /**
     * Gets the value of the exportPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link DateRangeCapped }
     *     
     */
    public DateRangeCapped getExportPeriod() {
        return exportPeriod;
    }

    /**
     * Sets the value of the exportPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRangeCapped }
     *     
     */
    public void setExportPeriod(DateRangeCapped value) {
        this.exportPeriod = value;
    }

    /**
     * Gets the value of the agency property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agency property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgency().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Agency }
     * 
     * 
     */
    public List<Agency> getAgency() {
        if (agency == null) {
            agency = new ArrayList<Agency>();
        }
        return this.agency;
    }

    /**
     * Gets the value of the household property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the household property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHousehold().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Household }
     * 
     * 
     */
    public List<Household> getHousehold() {
        if (household == null) {
            household = new ArrayList<Household>();
        }
        return this.household;
    }

    /**
     * Gets the value of the person property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the person property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPerson().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Person }
     * 
     * 
     */
    public List<Person> getPerson() {
        if (person == null) {
            person = new ArrayList<Person>();
        }
        return this.person;
    }

    /**
     * Gets the value of the service property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the service property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Service }
     * 
     * 
     */
    public List<Service> getService() {
        if (service == null) {
            service = new ArrayList<Service>();
        }
        return this.service;
    }

    /**
     * Gets the value of the site property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the site property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSite().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Site }
     * 
     * 
     */
    public List<Site> getSite() {
        if (site == null) {
            site = new ArrayList<Site>();
        }
        return this.site;
    }

    /**
     * Gets the value of the siteService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the siteService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSiteService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SiteService }
     * 
     * 
     */
    public List<SiteService> getSiteService() {
        if (siteService == null) {
            siteService = new ArrayList<SiteService>();
        }
        return this.siteService;
    }

}
