//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fundingSourceBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fundingSourceBase">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FundingSourceID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}iDIndex"/>
 *         &lt;element name="FederalCFDA" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}cFDANumber" minOccurs="0"/>
 *         &lt;element name="ReceivesMcKinneyFunding" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}twoValBase" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fundingSourceBase", propOrder = {
    "fundingSourceID",
    "federalCFDA",
    "receivesMcKinneyFunding"
})
@XmlSeeAlso({
    FundingSourceServiceEvent.class
})
public class FundingSourceBase {

    @XmlElement(name = "FundingSourceID", required = true)
    protected IDIndex fundingSourceID;
    @XmlElement(name = "FederalCFDA")
    protected BigDecimal federalCFDA;
    @XmlElement(name = "ReceivesMcKinneyFunding")
    protected Long receivesMcKinneyFunding;

    /**
     * Gets the value of the fundingSourceID property.
     * 
     * @return
     *     possible object is
     *     {@link IDIndex }
     *     
     */
    public IDIndex getFundingSourceID() {
        return fundingSourceID;
    }

    /**
     * Sets the value of the fundingSourceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDIndex }
     *     
     */
    public void setFundingSourceID(IDIndex value) {
        this.fundingSourceID = value;
    }

    /**
     * Gets the value of the federalCFDA property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFederalCFDA() {
        return federalCFDA;
    }

    /**
     * Sets the value of the federalCFDA property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFederalCFDA(BigDecimal value) {
        this.federalCFDA = value;
    }

    /**
     * Gets the value of the receivesMcKinneyFunding property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getReceivesMcKinneyFunding() {
        return receivesMcKinneyFunding;
    }

    /**
     * Sets the value of the receivesMcKinneyFunding property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setReceivesMcKinneyFunding(Long value) {
        this.receivesMcKinneyFunding = value;
    }

}
