//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hMISServiceEvent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hMISServiceEvent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TypeOfService" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}typeOfService" minOccurs="0"/>
 *         &lt;element name="TypeOfServiceOther" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}string50Base" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hMISServiceEvent", propOrder = {
    "typeOfService",
    "typeOfServiceOther"
})
public class HMISServiceEvent {

    @XmlElement(name = "TypeOfService")
    protected Long typeOfService;
    @XmlElement(name = "TypeOfServiceOther")
    protected String typeOfServiceOther;

    /**
     * Gets the value of the typeOfService property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTypeOfService() {
        return typeOfService;
    }

    /**
     * Sets the value of the typeOfService property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTypeOfService(Long value) {
        this.typeOfService = value;
    }

    /**
     * Gets the value of the typeOfServiceOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfServiceOther() {
        return typeOfServiceOther;
    }

    /**
     * Sets the value of the typeOfServiceOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfServiceOther(String value) {
        this.typeOfServiceOther = value;
    }

}
