//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for household complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="household">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HouseholdID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}iDIndex"/>
 *         &lt;element name="HeadOfHouseholdID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}iDIndexStamped" minOccurs="0"/>
 *         &lt;element name="Members" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}members" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "household", propOrder = {
    "householdID",
    "headOfHouseholdID",
    "members"
})
public class Household {

    @XmlElement(name = "HouseholdID", required = true)
    protected IDIndex householdID;
    @XmlElement(name = "HeadOfHouseholdID")
    protected IDIndexStamped headOfHouseholdID;
    @XmlElement(name = "Members")
    protected Members members;

    /**
     * Gets the value of the householdID property.
     * 
     * @return
     *     possible object is
     *     {@link IDIndex }
     *     
     */
    public IDIndex getHouseholdID() {
        return householdID;
    }

    /**
     * Sets the value of the householdID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDIndex }
     *     
     */
    public void setHouseholdID(IDIndex value) {
        this.householdID = value;
    }

    /**
     * Gets the value of the headOfHouseholdID property.
     * 
     * @return
     *     possible object is
     *     {@link IDIndexStamped }
     *     
     */
    public IDIndexStamped getHeadOfHouseholdID() {
        return headOfHouseholdID;
    }

    /**
     * Sets the value of the headOfHouseholdID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDIndexStamped }
     *     
     */
    public void setHeadOfHouseholdID(IDIndexStamped value) {
        this.headOfHouseholdID = value;
    }

    /**
     * Gets the value of the members property.
     * 
     * @return
     *     possible object is
     *     {@link Members }
     *     
     */
    public Members getMembers() {
        return members;
    }

    /**
     * Sets the value of the members property.
     * 
     * @param value
     *     allowed object is
     *     {@link Members }
     *     
     */
    public void setMembers(Members value) {
        this.members = value;
    }

}
