//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for iDIndex complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="iDIndex">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="IDNum" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *           &lt;element name="IDStr" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}string32Base"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}deleteStampGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "iDIndex", propOrder = {
    "idNum",
    "idStr"
})
@XmlSeeAlso({
    IDIndexStamped.class
})
public class IDIndex {

    @XmlElement(name = "IDNum")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger idNum;
    @XmlElement(name = "IDStr")
    protected String idStr;
    @XmlAttribute(name = "delete", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd")
    protected Long delete;
    @XmlAttribute(name = "deleteOccurredDate", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar deleteOccurredDate;
    @XmlAttribute(name = "deleteEffective", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar deleteEffective;

    /**
     * Gets the value of the idNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIDNum() {
        return idNum;
    }

    /**
     * Sets the value of the idNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIDNum(BigInteger value) {
        this.idNum = value;
    }

    /**
     * Gets the value of the idStr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDStr() {
        return idStr;
    }

    /**
     * Sets the value of the idStr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDStr(String value) {
        this.idStr = value;
    }

    /**
     * Gets the value of the delete property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getDelete() {
        if (delete == null) {
            return  0L;
        } else {
            return delete;
        }
    }

    /**
     * Sets the value of the delete property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDelete(Long value) {
        this.delete = value;
    }

    /**
     * Gets the value of the deleteOccurredDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeleteOccurredDate() {
        return deleteOccurredDate;
    }

    /**
     * Sets the value of the deleteOccurredDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeleteOccurredDate(XMLGregorianCalendar value) {
        this.deleteOccurredDate = value;
    }

    /**
     * Gets the value of the deleteEffective property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeleteEffective() {
        return deleteEffective;
    }

    /**
     * Sets the value of the deleteEffective property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeleteEffective(XMLGregorianCalendar value) {
        this.deleteEffective = value;
    }

}
