//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for incomeSourceCode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="incomeSourceCode">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.hmis.info/schema/3_0/HUD_HMIS.xsd>incomeSourceCodeBase">
 *       &lt;attGroup ref="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}dateStampGroup"/>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "incomeSourceCode", propOrder = {
    "value"
})
public class IncomeSourceCode {

    @XmlValue
    protected long value;
    @XmlAttribute(name = "dateCollected", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateCollected;
    @XmlAttribute(name = "dateEffective", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateEffective;
    @XmlAttribute(name = "dataCollectionStage", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd")
    protected Long dataCollectionStage;

    /**
     * 
     * 				Income Source Code
     * 				1 = Earned Income (i.e., employment income)
     * 				2 = Unemployment Insurance 
     * 				3 = Supplemental Security Income (SSI)
     * 				4 = Social Security Disability Income (SSDI)
     * 				5 = Veteran's Disability Payment
     * 				6 = Private Disability Insurance
     * 				7 = Worker's Compensation
     * 				10 = Temporary Assistance for Needy Families (TANF) (or use local program name)
     * 				11 = General Assistance (GA) (or use local program name)
     * 				12 = Retirement Income from Social Security
     * 				13 = Veteran’s Pension
     * 				14 = Pension from a Former Job
     * 				15 = Child Support
     * 				16 = Alimony or Other Spousal Support
     * 				17 = Other Source
     * 			
     * 
     */
    public long getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(long value) {
        this.value = value;
    }

    /**
     * Gets the value of the dateCollected property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateCollected() {
        return dateCollected;
    }

    /**
     * Sets the value of the dateCollected property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateCollected(XMLGregorianCalendar value) {
        this.dateCollected = value;
    }

    /**
     * Gets the value of the dateEffective property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateEffective() {
        return dateEffective;
    }

    /**
     * Sets the value of the dateEffective property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateEffective(XMLGregorianCalendar value) {
        this.dateEffective = value;
    }

    /**
     * Gets the value of the dataCollectionStage property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDataCollectionStage() {
        return dataCollectionStage;
    }

    /**
     * Sets the value of the dataCollectionStage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDataCollectionStage(Long value) {
        this.dataCollectionStage = value;
    }

}
