//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for incomeAndSource complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="incomeAndSource">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IncomeAndSourceID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}iDIndex"/>
 *         &lt;sequence maxOccurs="unbounded">
 *           &lt;element name="IncomeSourceCode" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}incomeSourceCode"/>
 *           &lt;element name="IncomeSourceOther" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}string50" minOccurs="0"/>
 *           &lt;choice>
 *             &lt;element name="ReceivingIncomeSource" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}twoVal"/>
 *             &lt;element name="IncomeSourceAmount" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}nonNegativeInteger" minOccurs="0"/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "incomeAndSource", propOrder = {
    "incomeAndSourceID",
    "incomeSourceCodeAndIncomeSourceOtherAndReceivingIncomeSource"
})
public class IncomeAndSource {

    @XmlElement(name = "IncomeAndSourceID", required = true)
    protected IDIndex incomeAndSourceID;
    @XmlElements({
        @XmlElement(name = "IncomeSourceCode", required = true, type = IncomeSourceCode.class),
        @XmlElement(name = "IncomeSourceAmount", required = true, type = NonNegativeInteger.class),
        @XmlElement(name = "IncomeSourceOther", required = true, type = String50 .class),
        @XmlElement(name = "ReceivingIncomeSource", required = true, type = TwoVal.class)
    })
    protected List<Object> incomeSourceCodeAndIncomeSourceOtherAndReceivingIncomeSource;

    /**
     * Gets the value of the incomeAndSourceID property.
     * 
     * @return
     *     possible object is
     *     {@link IDIndex }
     *     
     */
    public IDIndex getIncomeAndSourceID() {
        return incomeAndSourceID;
    }

    /**
     * Sets the value of the incomeAndSourceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDIndex }
     *     
     */
    public void setIncomeAndSourceID(IDIndex value) {
        this.incomeAndSourceID = value;
    }

    /**
     * Gets the value of the incomeSourceCodeAndIncomeSourceOtherAndReceivingIncomeSource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incomeSourceCodeAndIncomeSourceOtherAndReceivingIncomeSource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncomeSourceCodeAndIncomeSourceOtherAndReceivingIncomeSource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IncomeSourceCode }
     * {@link NonNegativeInteger }
     * {@link String50 }
     * {@link TwoVal }
     * 
     * 
     */
    public List<Object> getIncomeSourceCodeAndIncomeSourceOtherAndReceivingIncomeSource() {
        if (incomeSourceCodeAndIncomeSourceOtherAndReceivingIncomeSource == null) {
            incomeSourceCodeAndIncomeSourceOtherAndReceivingIncomeSource = new ArrayList<Object>();
        }
        return this.incomeSourceCodeAndIncomeSourceOtherAndReceivingIncomeSource;
    }

}
