//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Based on 1/15/2010 "2010 Housing Inventory and 2010 Point-in-Time Homeless Persons Counts Data Collection Guidance"    
 * 
 * <p>Java class for inventory complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="inventory">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}bedAndUnitInfo">
 *       &lt;sequence>
 *         &lt;element name="InventoryID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}iDIndex"/>
 *         &lt;element name="BedInventory" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}bedCountBase" minOccurs="0"/>
 *         &lt;element name="HMISParticipatingBeds" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="InventoryEffectivePeriod" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}dateRangeOpen" minOccurs="0"/>
 *         &lt;element name="InventoryRecordedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="UnitInventory" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inventory", propOrder = {
    "inventoryID",
    "bedInventory",
    "hmisParticipatingBeds",
    "inventoryEffectivePeriod",
    "inventoryRecordedDate",
    "unitInventory"
})
public class Inventory
    extends BedAndUnitInfo
{

    @XmlElement(name = "InventoryID", required = true)
    protected IDIndex inventoryID;
    @XmlElement(name = "BedInventory")
    protected BedCountBase bedInventory;
    @XmlElement(name = "HMISParticipatingBeds")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger hmisParticipatingBeds;
    @XmlElement(name = "InventoryEffectivePeriod")
    protected DateRangeOpen inventoryEffectivePeriod;
    @XmlElement(name = "InventoryRecordedDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar inventoryRecordedDate;
    @XmlElement(name = "UnitInventory")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger unitInventory;

    /**
     * Gets the value of the inventoryID property.
     * 
     * @return
     *     possible object is
     *     {@link IDIndex }
     *     
     */
    public IDIndex getInventoryID() {
        return inventoryID;
    }

    /**
     * Sets the value of the inventoryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDIndex }
     *     
     */
    public void setInventoryID(IDIndex value) {
        this.inventoryID = value;
    }

    /**
     * Gets the value of the bedInventory property.
     * 
     * @return
     *     possible object is
     *     {@link BedCountBase }
     *     
     */
    public BedCountBase getBedInventory() {
        return bedInventory;
    }

    /**
     * Sets the value of the bedInventory property.
     * 
     * @param value
     *     allowed object is
     *     {@link BedCountBase }
     *     
     */
    public void setBedInventory(BedCountBase value) {
        this.bedInventory = value;
    }

    /**
     * Gets the value of the hmisParticipatingBeds property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHMISParticipatingBeds() {
        return hmisParticipatingBeds;
    }

    /**
     * Sets the value of the hmisParticipatingBeds property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHMISParticipatingBeds(BigInteger value) {
        this.hmisParticipatingBeds = value;
    }

    /**
     * Gets the value of the inventoryEffectivePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link DateRangeOpen }
     *     
     */
    public DateRangeOpen getInventoryEffectivePeriod() {
        return inventoryEffectivePeriod;
    }

    /**
     * Sets the value of the inventoryEffectivePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRangeOpen }
     *     
     */
    public void setInventoryEffectivePeriod(DateRangeOpen value) {
        this.inventoryEffectivePeriod = value;
    }

    /**
     * Gets the value of the inventoryRecordedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInventoryRecordedDate() {
        return inventoryRecordedDate;
    }

    /**
     * Sets the value of the inventoryRecordedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInventoryRecordedDate(XMLGregorianCalendar value) {
        this.inventoryRecordedDate = value;
    }

    /**
     * Gets the value of the unitInventory property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUnitInventory() {
        return unitInventory;
    }

    /**
     * Sets the value of the unitInventory property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUnitInventory(BigInteger value) {
        this.unitInventory = value;
    }

}
