//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for member complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="member">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PersonID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}iDIndexStamped"/>
 *         &lt;element name="RelationshipToHeadOfHousehold" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}fourVal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "member", propOrder = {
    "personID",
    "relationshipToHeadOfHousehold"
})
public class Member {

    @XmlElement(name = "PersonID", required = true)
    protected IDIndexStamped personID;
    @XmlElement(name = "RelationshipToHeadOfHousehold")
    protected FourVal relationshipToHeadOfHousehold;

    /**
     * Gets the value of the personID property.
     * 
     * @return
     *     possible object is
     *     {@link IDIndexStamped }
     *     
     */
    public IDIndexStamped getPersonID() {
        return personID;
    }

    /**
     * Sets the value of the personID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDIndexStamped }
     *     
     */
    public void setPersonID(IDIndexStamped value) {
        this.personID = value;
    }

    /**
     * Gets the value of the relationshipToHeadOfHousehold property.
     * 
     * @return
     *     possible object is
     *     {@link FourVal }
     *     
     */
    public FourVal getRelationshipToHeadOfHousehold() {
        return relationshipToHeadOfHousehold;
    }

    /**
     * Sets the value of the relationshipToHeadOfHousehold property.
     * 
     * @param value
     *     allowed object is
     *     {@link FourVal }
     *     
     */
    public void setRelationshipToHeadOfHousehold(FourVal value) {
        this.relationshipToHeadOfHousehold = value;
    }

}
