//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mentalHealthProblem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mentalHealthProblem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HasMentalHealthProblem" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}fourValDKRefused"/>
 *         &lt;element name="MentalHealthIndefinite" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}fourValDKRefused" minOccurs="0"/>
 *         &lt;element name="ReceiveMentalHealthServices" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}fourValDKRefused" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mentalHealthProblem", propOrder = {
    "hasMentalHealthProblem",
    "mentalHealthIndefinite",
    "receiveMentalHealthServices"
})
public class MentalHealthProblem {

    @XmlElement(name = "HasMentalHealthProblem", required = true)
    protected FourValDKRefused hasMentalHealthProblem;
    @XmlElement(name = "MentalHealthIndefinite")
    protected FourValDKRefused mentalHealthIndefinite;
    @XmlElement(name = "ReceiveMentalHealthServices")
    protected FourValDKRefused receiveMentalHealthServices;

    /**
     * Gets the value of the hasMentalHealthProblem property.
     * 
     * @return
     *     possible object is
     *     {@link FourValDKRefused }
     *     
     */
    public FourValDKRefused getHasMentalHealthProblem() {
        return hasMentalHealthProblem;
    }

    /**
     * Sets the value of the hasMentalHealthProblem property.
     * 
     * @param value
     *     allowed object is
     *     {@link FourValDKRefused }
     *     
     */
    public void setHasMentalHealthProblem(FourValDKRefused value) {
        this.hasMentalHealthProblem = value;
    }

    /**
     * Gets the value of the mentalHealthIndefinite property.
     * 
     * @return
     *     possible object is
     *     {@link FourValDKRefused }
     *     
     */
    public FourValDKRefused getMentalHealthIndefinite() {
        return mentalHealthIndefinite;
    }

    /**
     * Sets the value of the mentalHealthIndefinite property.
     * 
     * @param value
     *     allowed object is
     *     {@link FourValDKRefused }
     *     
     */
    public void setMentalHealthIndefinite(FourValDKRefused value) {
        this.mentalHealthIndefinite = value;
    }

    /**
     * Gets the value of the receiveMentalHealthServices property.
     * 
     * @return
     *     possible object is
     *     {@link FourValDKRefused }
     *     
     */
    public FourValDKRefused getReceiveMentalHealthServices() {
        return receiveMentalHealthServices;
    }

    /**
     * Sets the value of the receiveMentalHealthServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link FourValDKRefused }
     *     
     */
    public void setReceiveMentalHealthServices(FourValDKRefused value) {
        this.receiveMentalHealthServices = value;
    }

}
