//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import org.pathways.openciss.info.hmis.schema._3_0.airs_3_0_mod.TTaxonomy;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for need complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="need">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NeedID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}iDIndex"/>
 *         &lt;element name="SiteServiceID" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="ServiceEventID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}id" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="NeedEffectivePeriod" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}dateRangeOpen" minOccurs="0"/>
 *         &lt;element name="NeedRecordedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="NeedStatus" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}threeValBase"/>
 *         &lt;element name="Taxonomy" type="{http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd}tTaxonomy" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "need", propOrder = {
    "needID",
    "siteServiceID",
    "serviceEventID",
    "needEffectivePeriod",
    "needRecordedDate",
    "needStatus",
    "taxonomy"
})
public class Need {

    @XmlElement(name = "NeedID", required = true)
    protected IDIndex needID;
    @XmlElement(name = "SiteServiceID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger siteServiceID;
    @XmlElement(name = "ServiceEventID")
    protected List<Id> serviceEventID;
    @XmlElement(name = "NeedEffectivePeriod")
    protected DateRangeOpen needEffectivePeriod;
    @XmlElement(name = "NeedRecordedDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar needRecordedDate;
    @XmlElement(name = "NeedStatus")
    protected long needStatus;
    @XmlElement(name = "Taxonomy")
    protected TTaxonomy taxonomy;

    /**
     * Gets the value of the needID property.
     * 
     * @return
     *     possible object is
     *     {@link IDIndex }
     *     
     */
    public IDIndex getNeedID() {
        return needID;
    }

    /**
     * Sets the value of the needID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDIndex }
     *     
     */
    public void setNeedID(IDIndex value) {
        this.needID = value;
    }

    /**
     * Gets the value of the siteServiceID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSiteServiceID() {
        return siteServiceID;
    }

    /**
     * Sets the value of the siteServiceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSiteServiceID(BigInteger value) {
        this.siteServiceID = value;
    }

    /**
     * Gets the value of the serviceEventID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviceEventID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceEventID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Id }
     * 
     * 
     */
    public List<Id> getServiceEventID() {
        if (serviceEventID == null) {
            serviceEventID = new ArrayList<Id>();
        }
        return this.serviceEventID;
    }

    /**
     * Gets the value of the needEffectivePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link DateRangeOpen }
     *     
     */
    public DateRangeOpen getNeedEffectivePeriod() {
        return needEffectivePeriod;
    }

    /**
     * Sets the value of the needEffectivePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRangeOpen }
     *     
     */
    public void setNeedEffectivePeriod(DateRangeOpen value) {
        this.needEffectivePeriod = value;
    }

    /**
     * Gets the value of the needRecordedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNeedRecordedDate() {
        return needRecordedDate;
    }

    /**
     * Sets the value of the needRecordedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNeedRecordedDate(XMLGregorianCalendar value) {
        this.needRecordedDate = value;
    }

    /**
     * Gets the value of the needStatus property.
     * 
     */
    public long getNeedStatus() {
        return needStatus;
    }

    /**
     * Sets the value of the needStatus property.
     * 
     */
    public void setNeedStatus(long value) {
        this.needStatus = value;
    }

    /**
     * Gets the value of the taxonomy property.
     * 
     * @return
     *     possible object is
     *     {@link TTaxonomy }
     *     
     */
    public TTaxonomy getTaxonomy() {
        return taxonomy;
    }

    /**
     * Sets the value of the taxonomy property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTaxonomy }
     *     
     */
    public void setTaxonomy(TTaxonomy value) {
        this.taxonomy = value;
    }

}
