//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the info.hmis.schema._3_0.hud_hmis package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Sources_QNAME = new QName("http://www.hmis.info/schema/3_0/HUD_HMIS.xsd", "Sources");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: info.hmis.schema._3_0.hud_hmis
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServiceEvent }
     * 
     */
    public ServiceEvent createServiceEvent() {
        return new ServiceEvent();
    }

    /**
     * Create an instance of {@link FourValDKRefusedStatic }
     * 
     */
    public FourValDKRefusedStatic createFourValDKRefusedStatic() {
        return new FourValDKRefusedStatic();
    }

    /**
     * Create an instance of {@link FundingSourceBase }
     * 
     */
    public FundingSourceBase createFundingSourceBase() {
        return new FundingSourceBase();
    }

    /**
     * Create an instance of {@link Email }
     * 
     */
    public Email createEmail() {
        return new Email();
    }

    /**
     * Create an instance of {@link SevenVal }
     * 
     */
    public SevenVal createSevenVal() {
        return new SevenVal();
    }

    /**
     * Create an instance of {@link ChronicHealthCondition }
     * 
     */
    public ChronicHealthCondition createChronicHealthCondition() {
        return new ChronicHealthCondition();
    }

    /**
     * Create an instance of {@link State }
     * 
     */
    public State createState() {
        return new State();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link Notes }
     * 
     */
    public Notes createNotes() {
        return new Notes();
    }

    /**
     * Create an instance of {@link ServiceEra }
     * 
     */
    public ServiceEra createServiceEra() {
        return new ServiceEra();
    }

    /**
     * Create an instance of {@link PriorResidence }
     * 
     */
    public PriorResidence createPriorResidence() {
        return new PriorResidence();
    }

    /**
     * Create an instance of {@link IDIndex }
     * 
     */
    public IDIndex createIDIndex() {
        return new IDIndex();
    }

    /**
     * Create an instance of {@link Degree }
     * 
     */
    public Degree createDegree() {
        return new Degree();
    }

    /**
     * Create an instance of {@link DestinationCode }
     * 
     */
    public DestinationCode createDestinationCode() {
        return new DestinationCode();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link PITCountSet }
     * 
     */
    public PITCountSet createPITCountSet() {
        return new PITCountSet();
    }

    /**
     * Create an instance of {@link Inventory }
     * 
     */
    public Inventory createInventory() {
        return new Inventory();
    }

    /**
     * Create an instance of {@link Agency }
     * 
     */
    public Agency createAgency() {
        return new Agency();
    }

    /**
     * Create an instance of {@link HealthStatus }
     * 
     */
    public HealthStatus createHealthStatus() {
        return new HealthStatus();
    }

    /**
     * Create an instance of {@link BedAndUnitInfo }
     * 
     */
    public BedAndUnitInfo createBedAndUnitInfo() {
        return new BedAndUnitInfo();
    }

    /**
     * Create an instance of {@link ContactLocation }
     * 
     */
    public ContactLocation createContactLocation() {
        return new ContactLocation();
    }

    /**
     * Create an instance of {@link OtherNames }
     * 
     */
    public OtherNames createOtherNames() {
        return new OtherNames();
    }

    /**
     * Create an instance of {@link DegreeCode }
     * 
     */
    public DegreeCode createDegreeCode() {
        return new DegreeCode();
    }

    /**
     * Create an instance of {@link ReleaseOfInformation }
     * 
     */
    public ReleaseOfInformation createReleaseOfInformation() {
        return new ReleaseOfInformation();
    }

    /**
     * Create an instance of {@link DateRangeCapped }
     * 
     */
    public DateRangeCapped createDateRangeCapped() {
        return new DateRangeCapped();
    }

    /**
     * Create an instance of {@link FourVal }
     * 
     */
    public FourVal createFourVal() {
        return new FourVal();
    }

    /**
     * Create an instance of {@link HMISServiceEvent }
     * 
     */
    public HMISServiceEvent createHMISServiceEvent() {
        return new HMISServiceEvent();
    }

    /**
     * Create an instance of {@link Sources }
     * 
     */
    public Sources createSources() {
        return new Sources();
    }

    /**
     * Create an instance of {@link ChildEnrollmentStatus }
     * 
     */
    public ChildEnrollmentStatus createChildEnrollmentStatus() {
        return new ChildEnrollmentStatus();
    }

    /**
     * Create an instance of {@link String30 }
     * 
     */
    public String30 createString30() {
        return new String30();
    }

    /**
     * Create an instance of {@link Regions }
     * 
     */
    public Regions createRegions() {
        return new Regions();
    }

    /**
     * Create an instance of {@link ElevenVal }
     * 
     */
    public ElevenVal createElevenVal() {
        return new ElevenVal();
    }

    /**
     * Create an instance of {@link PersonAddressBase }
     * 
     */
    public PersonAddressBase createPersonAddressBase() {
        return new PersonAddressBase();
    }

    /**
     * Create an instance of {@link PersonHistorical }
     * 
     */
    public PersonHistorical createPersonHistorical() {
        return new PersonHistorical();
    }

    /**
     * Create an instance of {@link FundingSourcesService }
     * 
     */
    public FundingSourcesService createFundingSourcesService() {
        return new FundingSourcesService();
    }

    /**
     * Create an instance of {@link String50 }
     * 
     */
    public String50 createString50() {
        return new String50();
    }

    /**
     * Create an instance of {@link WarZoneServed }
     * 
     */
    public WarZoneServed createWarZoneServed() {
        return new WarZoneServed();
    }

    /**
     * Create an instance of {@link DateRangeOpen }
     * 
     */
    public DateRangeOpen createDateRangeOpen() {
        return new DateRangeOpen();
    }

    /**
     * Create an instance of {@link Destination }
     * 
     */
    public Destination createDestination() {
        return new Destination();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link WarZone }
     * 
     */
    public WarZone createWarZone() {
        return new WarZone();
    }

    /**
     * Create an instance of {@link MentalHealthProblem }
     * 
     */
    public MentalHealthProblem createMentalHealthProblem() {
        return new MentalHealthProblem();
    }

    /**
     * Create an instance of {@link Residence }
     * 
     */
    public Residence createResidence() {
        return new Residence();
    }

    /**
     * Create an instance of {@link PersonAddress }
     * 
     */
    public PersonAddress createPersonAddress() {
        return new PersonAddress();
    }

    /**
     * Create an instance of {@link FourValDKRefused }
     * 
     */
    public FourValDKRefused createFourValDKRefused() {
        return new FourValDKRefused();
    }

    /**
     * Create an instance of {@link DevelopmentalDisability }
     * 
     */
    public DevelopmentalDisability createDevelopmentalDisability() {
        return new DevelopmentalDisability();
    }

    /**
     * Create an instance of {@link FundingSourcesServiceEvent }
     * 
     */
    public FundingSourcesServiceEvent createFundingSourcesServiceEvent() {
        return new FundingSourcesServiceEvent();
    }

    /**
     * Create an instance of {@link DischargeStatus }
     * 
     */
    public DischargeStatus createDischargeStatus() {
        return new DischargeStatus();
    }

    /**
     * Create an instance of {@link ContactDate }
     * 
     */
    public ContactDate createContactDate() {
        return new ContactDate();
    }

    /**
     * Create an instance of {@link AddressBase }
     * 
     */
    public AddressBase createAddressBase() {
        return new AddressBase();
    }

    /**
     * Create an instance of {@link Date }
     * 
     */
    public Date createDate() {
        return new Date();
    }

    /**
     * Create an instance of {@link PITCounts }
     * 
     */
    public PITCounts createPITCounts() {
        return new PITCounts();
    }

    /**
     * Create an instance of {@link SevenValDKRefused2Static }
     * 
     */
    public SevenValDKRefused2Static createSevenValDKRefused2Static() {
        return new SevenValDKRefused2Static();
    }

    /**
     * Create an instance of {@link ZIPQualityCode }
     * 
     */
    public ZIPQualityCode createZIPQualityCode() {
        return new ZIPQualityCode();
    }

    /**
     * Create an instance of {@link String100 }
     * 
     */
    public String100 createString100() {
        return new String100();
    }

    /**
     * Create an instance of {@link SevenValDKRefusedHashingChoice }
     * 
     */
    public SevenValDKRefusedHashingChoice createSevenValDKRefusedHashingChoice() {
        return new SevenValDKRefusedHashingChoice();
    }

    /**
     * Create an instance of {@link NonCashBenefits }
     * 
     */
    public NonCashBenefits createNonCashBenefits() {
        return new NonCashBenefits();
    }

    /**
     * Create an instance of {@link SevenValDKRefused2HashingChoiceStatic }
     * 
     */
    public SevenValDKRefused2HashingChoiceStatic createSevenValDKRefused2HashingChoiceStatic() {
        return new SevenValDKRefused2HashingChoiceStatic();
    }

    /**
     * Create an instance of {@link Member }
     * 
     */
    public Member createMember() {
        return new Member();
    }

    /**
     * Create an instance of {@link SSNHashingChoice }
     * 
     */
    public SSNHashingChoice createSSNHashingChoice() {
        return new SSNHashingChoice();
    }

    /**
     * Create an instance of {@link Employment }
     * 
     */
    public Employment createEmployment() {
        return new Employment();
    }

    /**
     * Create an instance of {@link IncomeAndSource }
     * 
     */
    public IncomeAndSource createIncomeAndSource() {
        return new IncomeAndSource();
    }

    /**
     * Create an instance of {@link BarrierCode }
     * 
     */
    public BarrierCode createBarrierCode() {
        return new BarrierCode();
    }

    /**
     * Create an instance of {@link HashingChoiceStamped }
     * 
     */
    public HashingChoiceStamped createHashingChoiceStamped() {
        return new HashingChoiceStamped();
    }

    /**
     * Create an instance of {@link FiveValDKRefused }
     * 
     */
    public FiveValDKRefused createFiveValDKRefused() {
        return new FiveValDKRefused();
    }

    /**
     * Create an instance of {@link HMISAsset }
     * 
     */
    public HMISAsset createHMISAsset() {
        return new HMISAsset();
    }

    /**
     * Create an instance of {@link HighestSchoolLevel }
     * 
     */
    public HighestSchoolLevel createHighestSchoolLevel() {
        return new HighestSchoolLevel();
    }

    /**
     * Create an instance of {@link Veteran }
     * 
     */
    public Veteran createVeteran() {
        return new Veteran();
    }

    /**
     * Create an instance of {@link Asset }
     * 
     */
    public Asset createAsset() {
        return new Asset();
    }

    /**
     * Create an instance of {@link DomesticViolence }
     * 
     */
    public DomesticViolence createDomesticViolence() {
        return new DomesticViolence();
    }

    /**
     * Create an instance of {@link NonCashBenefit }
     * 
     */
    public NonCashBenefit createNonCashBenefit() {
        return new NonCashBenefit();
    }

    /**
     * Create an instance of {@link Members }
     * 
     */
    public Members createMembers() {
        return new Members();
    }

    /**
     * Create an instance of {@link String255 }
     * 
     */
    public String255 createString255() {
        return new String255();
    }

    /**
     * Create an instance of {@link SiteServiceParticipation }
     * 
     */
    public SiteServiceParticipation createSiteServiceParticipation() {
        return new SiteServiceParticipation();
    }

    /**
     * Create an instance of {@link Barrier }
     * 
     */
    public Barrier createBarrier() {
        return new Barrier();
    }

    /**
     * Create an instance of {@link DOBHashingChoice }
     * 
     */
    public DOBHashingChoice createDOBHashingChoice() {
        return new DOBHashingChoice();
    }

    /**
     * Create an instance of {@link MilitaryBranches }
     * 
     */
    public MilitaryBranches createMilitaryBranches() {
        return new MilitaryBranches();
    }

    /**
     * Create an instance of {@link SiteService }
     * 
     */
    public SiteService createSiteService() {
        return new SiteService();
    }

    /**
     * Create an instance of {@link Export }
     * 
     */
    public Export createExport() {
        return new Export();
    }

    /**
     * Create an instance of {@link Region }
     * 
     */
    public Region createRegion() {
        return new Region();
    }

    /**
     * Create an instance of {@link PhoneNumber }
     * 
     */
    public PhoneNumber createPhoneNumber() {
        return new PhoneNumber();
    }

    /**
     * Create an instance of {@link ContactsMade }
     * 
     */
    public ContactsMade createContactsMade() {
        return new ContactsMade();
    }

    /**
     * Create an instance of {@link FourValDKRefused2 }
     * 
     */
    public FourValDKRefused2 createFourValDKRefused2() {
        return new FourValDKRefused2();
    }

    /**
     * Create an instance of {@link Id }
     * 
     */
    public Id createId() {
        return new Id();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link ZIPCode }
     * 
     */
    public ZIPCode createZIPCode() {
        return new ZIPCode();
    }

    /**
     * Create an instance of {@link IDIndexStamped }
     * 
     */
    public IDIndexStamped createIDIndexStamped() {
        return new IDIndexStamped();
    }

    /**
     * Create an instance of {@link NonNegativeInteger }
     * 
     */
    public NonNegativeInteger createNonNegativeInteger() {
        return new NonNegativeInteger();
    }

    /**
     * Create an instance of {@link PhysicalDisability }
     * 
     */
    public PhysicalDisability createPhysicalDisability() {
        return new PhysicalDisability();
    }

    /**
     * Create an instance of {@link Household }
     * 
     */
    public Household createHousehold() {
        return new Household();
    }

    /**
     * Create an instance of {@link DateStatic }
     * 
     */
    public DateStatic createDateStatic() {
        return new DateStatic();
    }

    /**
     * Create an instance of {@link TwoVal }
     * 
     */
    public TwoVal createTwoVal() {
        return new TwoVal();
    }

    /**
     * Create an instance of {@link ContactMade }
     * 
     */
    public ContactMade createContactMade() {
        return new ContactMade();
    }

    /**
     * Create an instance of {@link Destinations }
     * 
     */
    public Destinations createDestinations() {
        return new Destinations();
    }

    /**
     * Create an instance of {@link Need }
     * 
     */
    public Need createNeed() {
        return new Need();
    }

    /**
     * Create an instance of {@link IncomeAndSources }
     * 
     */
    public IncomeAndSources createIncomeAndSources() {
        return new IncomeAndSources();
    }

    /**
     * Create an instance of {@link GeographicCode }
     * 
     */
    public GeographicCode createGeographicCode() {
        return new GeographicCode();
    }

    /**
     * Create an instance of {@link SixValDKRefused2 }
     * 
     */
    public SixValDKRefused2 createSixValDKRefused2() {
        return new SixValDKRefused2();
    }

    /**
     * Create an instance of {@link BedCountBase }
     * 
     */
    public BedCountBase createBedCountBase() {
        return new BedCountBase();
    }

    /**
     * Create an instance of {@link IncomeSourceCode }
     * 
     */
    public IncomeSourceCode createIncomeSourceCode() {
        return new IncomeSourceCode();
    }

    /**
     * Create an instance of {@link ReasonForLeaving }
     * 
     */
    public ReasonForLeaving createReasonForLeaving() {
        return new ReasonForLeaving();
    }

    /**
     * Create an instance of {@link FundingSourceServiceEvent }
     * 
     */
    public FundingSourceServiceEvent createFundingSourceServiceEvent() {
        return new FundingSourceServiceEvent();
    }

    /**
     * Create an instance of {@link Assignment }
     * 
     */
    public Assignment createAssignment() {
        return new Assignment();
    }

    /**
     * Create an instance of {@link SSNumber }
     * 
     */
    public SSNumber createSSNumber() {
        return new SSNumber();
    }

    /**
     * Create an instance of {@link SubstanceAbuseProblem }
     * 
     */
    public SubstanceAbuseProblem createSubstanceAbuseProblem() {
        return new SubstanceAbuseProblem();
    }

    /**
     * Create an instance of {@link NonCashSourceCode }
     * 
     */
    public NonCashSourceCode createNonCashSourceCode() {
        return new NonCashSourceCode();
    }

    /**
     * Create an instance of {@link PITCount }
     * 
     */
    public PITCount createPITCount() {
        return new PITCount();
    }

    /**
     * Create an instance of {@link HIVAIDSStatus }
     * 
     */
    public HIVAIDSStatus createHIVAIDSStatus() {
        return new HIVAIDSStatus();
    }

    /**
     * Create an instance of {@link SixValDKRefused }
     * 
     */
    public SixValDKRefused createSixValDKRefused() {
        return new SixValDKRefused();
    }

    /**
     * Create an instance of {@link Site }
     * 
     */
    public Site createSite() {
        return new Site();
    }

    /**
     * Create an instance of {@link Pregnancy }
     * 
     */
    public Pregnancy createPregnancy() {
        return new Pregnancy();
    }

    /**
     * Create an instance of {@link SevenValDKRefused }
     * 
     */
    public SevenValDKRefused createSevenValDKRefused() {
        return new SevenValDKRefused();
    }

    /**
     * Create an instance of {@link SevenValDKRefused2 }
     * 
     */
    public SevenValDKRefused2 createSevenValDKRefused2() {
        return new SevenValDKRefused2();
    }

    /**
     * Create an instance of {@link FourValDKRefusedHashingChoice }
     * 
     */
    public FourValDKRefusedHashingChoice createFourValDKRefusedHashingChoice() {
        return new FourValDKRefusedHashingChoice();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sources }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd", name = "Sources")
    public JAXBElement<Sources> createSources(Sources value) {
        return new JAXBElement<Sources>(_Sources_QNAME, Sources.class, null, value);
    }

}
