//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for otherNames complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="otherNames">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OtherFirstName" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}hashingChoiceStamped" minOccurs="0"/>
 *         &lt;element name="OtherMiddleName" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}hashingChoiceStamped" minOccurs="0"/>
 *         &lt;element name="OtherLastName" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}hashingChoiceStamped" minOccurs="0"/>
 *         &lt;element name="OtherSuffix" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}hashingChoiceStamped" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "otherNames", propOrder = {
    "otherFirstName",
    "otherMiddleName",
    "otherLastName",
    "otherSuffix"
})
public class OtherNames {

    @XmlElement(name = "OtherFirstName")
    protected HashingChoiceStamped otherFirstName;
    @XmlElement(name = "OtherMiddleName")
    protected HashingChoiceStamped otherMiddleName;
    @XmlElement(name = "OtherLastName")
    protected HashingChoiceStamped otherLastName;
    @XmlElement(name = "OtherSuffix")
    protected HashingChoiceStamped otherSuffix;

    /**
     * Gets the value of the otherFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link HashingChoiceStamped }
     *     
     */
    public HashingChoiceStamped getOtherFirstName() {
        return otherFirstName;
    }

    /**
     * Sets the value of the otherFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link HashingChoiceStamped }
     *     
     */
    public void setOtherFirstName(HashingChoiceStamped value) {
        this.otherFirstName = value;
    }

    /**
     * Gets the value of the otherMiddleName property.
     * 
     * @return
     *     possible object is
     *     {@link HashingChoiceStamped }
     *     
     */
    public HashingChoiceStamped getOtherMiddleName() {
        return otherMiddleName;
    }

    /**
     * Sets the value of the otherMiddleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link HashingChoiceStamped }
     *     
     */
    public void setOtherMiddleName(HashingChoiceStamped value) {
        this.otherMiddleName = value;
    }

    /**
     * Gets the value of the otherLastName property.
     * 
     * @return
     *     possible object is
     *     {@link HashingChoiceStamped }
     *     
     */
    public HashingChoiceStamped getOtherLastName() {
        return otherLastName;
    }

    /**
     * Sets the value of the otherLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link HashingChoiceStamped }
     *     
     */
    public void setOtherLastName(HashingChoiceStamped value) {
        this.otherLastName = value;
    }

    /**
     * Gets the value of the otherSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link HashingChoiceStamped }
     *     
     */
    public HashingChoiceStamped getOtherSuffix() {
        return otherSuffix;
    }

    /**
     * Sets the value of the otherSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link HashingChoiceStamped }
     *     
     */
    public void setOtherSuffix(HashingChoiceStamped value) {
        this.otherSuffix = value;
    }

}
