//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for person complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="person">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PersonID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}iDIndex"/>
 *         &lt;element name="DateOfBirth" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}dOBHashingChoice" minOccurs="0"/>
 *         &lt;element name="Ethnicity" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}fourValDKRefusedHashingChoice" minOccurs="0"/>
 *         &lt;element name="Gender" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}sevenValDKRefusedHashingChoice" minOccurs="0"/>
 *         &lt;element name="LegalFirstName" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}hashingChoiceStamped" minOccurs="0"/>
 *         &lt;element name="LegalLastName" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}hashingChoiceStamped" minOccurs="0"/>
 *         &lt;element name="LegalMiddleName" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}hashingChoiceStamped" minOccurs="0"/>
 *         &lt;element name="LegalSuffix" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}hashingChoiceStamped" minOccurs="0"/>
 *         &lt;element name="Need" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}need" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OtherNames" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}otherNames" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PersonHistorical" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}personHistorical" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Race" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}sevenValDKRefused2HashingChoiceStatic" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ReleaseOfInformation" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}releaseOfInformation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ServiceEvent" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}serviceEvent" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SiteServiceParticipation" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}siteServiceParticipation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SocialSecurityNumber" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}sSNHashingChoice" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "Person")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "person", propOrder = {
    "personID",
    "dateOfBirth",
    "ethnicity",
    "gender",
    "legalFirstName",
    "legalLastName",
    "legalMiddleName",
    "legalSuffix",
    "need",
    "otherNames",
    "personHistorical",
    "race",
    "releaseOfInformation",
    "serviceEvent",
    "siteServiceParticipation",
    "socialSecurityNumber"
})
public class Person {

    @XmlElement(name = "PersonID", required = true)
    protected IDIndex personID;
    @XmlElement(name = "DateOfBirth")
    protected DOBHashingChoice dateOfBirth;
    @XmlElement(name = "Ethnicity")
    protected FourValDKRefusedHashingChoice ethnicity;
    @XmlElement(name = "Gender")
    protected SevenValDKRefusedHashingChoice gender;
    @XmlElement(name = "LegalFirstName")
    protected HashingChoiceStamped legalFirstName;
    @XmlElement(name = "LegalLastName")
    protected HashingChoiceStamped legalLastName;
    @XmlElement(name = "LegalMiddleName")
    protected HashingChoiceStamped legalMiddleName;
    @XmlElement(name = "LegalSuffix")
    protected HashingChoiceStamped legalSuffix;
    @XmlElement(name = "Need")
    protected List<Need> need;
    @XmlElement(name = "OtherNames")
    protected List<OtherNames> otherNames;
    @XmlElement(name = "PersonHistorical")
    protected List<PersonHistorical> personHistorical;
    @XmlElement(name = "Race")
    protected List<SevenValDKRefused2HashingChoiceStatic> race;
    @XmlElement(name = "ReleaseOfInformation")
    protected List<ReleaseOfInformation> releaseOfInformation;
    @XmlElement(name = "ServiceEvent")
    protected List<ServiceEvent> serviceEvent;
    @XmlElement(name = "SiteServiceParticipation")
    protected List<SiteServiceParticipation> siteServiceParticipation;
    @XmlElement(name = "SocialSecurityNumber")
    protected SSNHashingChoice socialSecurityNumber;

    /**
     * Gets the value of the personID property.
     * 
     * @return
     *     possible object is
     *     {@link IDIndex }
     *     
     */
    public IDIndex getPersonID() {
        return personID;
    }

    /**
     * Sets the value of the personID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDIndex }
     *     
     */
    public void setPersonID(IDIndex value) {
        this.personID = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link DOBHashingChoice }
     *     
     */
    public DOBHashingChoice getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOBHashingChoice }
     *     
     */
    public void setDateOfBirth(DOBHashingChoice value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the ethnicity property.
     * 
     * @return
     *     possible object is
     *     {@link FourValDKRefusedHashingChoice }
     *     
     */
    public FourValDKRefusedHashingChoice getEthnicity() {
        return ethnicity;
    }

    /**
     * Sets the value of the ethnicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link FourValDKRefusedHashingChoice }
     *     
     */
    public void setEthnicity(FourValDKRefusedHashingChoice value) {
        this.ethnicity = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link SevenValDKRefusedHashingChoice }
     *     
     */
    public SevenValDKRefusedHashingChoice getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link SevenValDKRefusedHashingChoice }
     *     
     */
    public void setGender(SevenValDKRefusedHashingChoice value) {
        this.gender = value;
    }

    /**
     * Gets the value of the legalFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link HashingChoiceStamped }
     *     
     */
    public HashingChoiceStamped getLegalFirstName() {
        return legalFirstName;
    }

    /**
     * Sets the value of the legalFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link HashingChoiceStamped }
     *     
     */
    public void setLegalFirstName(HashingChoiceStamped value) {
        this.legalFirstName = value;
    }

    /**
     * Gets the value of the legalLastName property.
     * 
     * @return
     *     possible object is
     *     {@link HashingChoiceStamped }
     *     
     */
    public HashingChoiceStamped getLegalLastName() {
        return legalLastName;
    }

    /**
     * Sets the value of the legalLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link HashingChoiceStamped }
     *     
     */
    public void setLegalLastName(HashingChoiceStamped value) {
        this.legalLastName = value;
    }

    /**
     * Gets the value of the legalMiddleName property.
     * 
     * @return
     *     possible object is
     *     {@link HashingChoiceStamped }
     *     
     */
    public HashingChoiceStamped getLegalMiddleName() {
        return legalMiddleName;
    }

    /**
     * Sets the value of the legalMiddleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link HashingChoiceStamped }
     *     
     */
    public void setLegalMiddleName(HashingChoiceStamped value) {
        this.legalMiddleName = value;
    }

    /**
     * Gets the value of the legalSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link HashingChoiceStamped }
     *     
     */
    public HashingChoiceStamped getLegalSuffix() {
        return legalSuffix;
    }

    /**
     * Sets the value of the legalSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link HashingChoiceStamped }
     *     
     */
    public void setLegalSuffix(HashingChoiceStamped value) {
        this.legalSuffix = value;
    }

    /**
     * Gets the value of the need property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the need property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNeed().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Need }
     * 
     * 
     */
    public List<Need> getNeed() {
        if (need == null) {
            need = new ArrayList<Need>();
        }
        return this.need;
    }

    /**
     * Gets the value of the otherNames property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherNames property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherNames().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OtherNames }
     * 
     * 
     */
    public List<OtherNames> getOtherNames() {
        if (otherNames == null) {
            otherNames = new ArrayList<OtherNames>();
        }
        return this.otherNames;
    }

    /**
     * Gets the value of the personHistorical property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personHistorical property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonHistorical().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonHistorical }
     * 
     * 
     */
    public List<PersonHistorical> getPersonHistorical() {
        if (personHistorical == null) {
            personHistorical = new ArrayList<PersonHistorical>();
        }
        return this.personHistorical;
    }

    /**
     * Gets the value of the race property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the race property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SevenValDKRefused2HashingChoiceStatic }
     * 
     * 
     */
    public List<SevenValDKRefused2HashingChoiceStatic> getRace() {
        if (race == null) {
            race = new ArrayList<SevenValDKRefused2HashingChoiceStatic>();
        }
        return this.race;
    }
    
    /**
     * Gets the value of the releaseOfInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the releaseOfInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReleaseOfInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReleaseOfInformation }
     * 
     * 
     */
    public List<ReleaseOfInformation> getReleaseOfInformation() {
        if (releaseOfInformation == null) {
            releaseOfInformation = new ArrayList<ReleaseOfInformation>();
        }
        return this.releaseOfInformation;
    }

    /**
     * Gets the value of the serviceEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviceEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceEvent }
     * 
     * 
     */
    public List<ServiceEvent> getServiceEvent() {
        if (serviceEvent == null) {
            serviceEvent = new ArrayList<ServiceEvent>();
        }
        return this.serviceEvent;
    }

    /**
     * Gets the value of the siteServiceParticipation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the siteServiceParticipation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSiteServiceParticipation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SiteServiceParticipation }
     * 
     * 
     */
    public List<SiteServiceParticipation> getSiteServiceParticipation() {
        if (siteServiceParticipation == null) {
            siteServiceParticipation = new ArrayList<SiteServiceParticipation>();
        }
        return this.siteServiceParticipation;
    }

    /**
     * Gets the value of the socialSecurityNumber property.
     * 
     * @return
     *     possible object is
     *     {@link SSNHashingChoice }
     *     
     */
    public SSNHashingChoice getSocialSecurityNumber() {
        return socialSecurityNumber;
    }

    /**
     * Sets the value of the socialSecurityNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link SSNHashingChoice }
     *     
     */
    public void setSocialSecurityNumber(SSNHashingChoice value) {
        this.socialSecurityNumber = value;
    }

}
