//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for personAddressBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="personAddressBase">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}addressBase">
 *       &lt;sequence>
 *         &lt;element name="IsLastPermanentZIP" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}twoVal" minOccurs="0"/>
 *         &lt;element name="ZIPQualityCode" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}zIPQualityCode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "personAddressBase", propOrder = {
    "isLastPermanentZIP",
    "zipQualityCode"
})
@XmlSeeAlso({
    PersonAddress.class
})
public class PersonAddressBase
    extends AddressBase
{

    @XmlElement(name = "IsLastPermanentZIP")
    protected TwoVal isLastPermanentZIP;
    @XmlElement(name = "ZIPQualityCode")
    protected ZIPQualityCode zipQualityCode;

    /**
     * Gets the value of the isLastPermanentZIP property.
     * 
     * @return
     *     possible object is
     *     {@link TwoVal }
     *     
     */
    public TwoVal getIsLastPermanentZIP() {
        return isLastPermanentZIP;
    }

    /**
     * Sets the value of the isLastPermanentZIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link TwoVal }
     *     
     */
    public void setIsLastPermanentZIP(TwoVal value) {
        this.isLastPermanentZIP = value;
    }

    /**
     * Gets the value of the zipQualityCode property.
     * 
     * @return
     *     possible object is
     *     {@link ZIPQualityCode }
     *     
     */
    public ZIPQualityCode getZIPQualityCode() {
        return zipQualityCode;
    }

    /**
     * Sets the value of the zipQualityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZIPQualityCode }
     *     
     */
    public void setZIPQualityCode(ZIPQualityCode value) {
        this.zipQualityCode = value;
    }

}
