//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for physicalDisability complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="physicalDisability">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HasPhysicalDisability" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}fourValDKRefused"/>
 *         &lt;element name="ReceivePhysicalDisabilityServices" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}fourValDKRefused" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "physicalDisability", propOrder = {
    "hasPhysicalDisability",
    "receivePhysicalDisabilityServices"
})
public class PhysicalDisability {

    @XmlElement(name = "HasPhysicalDisability", required = true)
    protected FourValDKRefused hasPhysicalDisability;
    @XmlElement(name = "ReceivePhysicalDisabilityServices")
    protected FourValDKRefused receivePhysicalDisabilityServices;

    /**
     * Gets the value of the hasPhysicalDisability property.
     * 
     * @return
     *     possible object is
     *     {@link FourValDKRefused }
     *     
     */
    public FourValDKRefused getHasPhysicalDisability() {
        return hasPhysicalDisability;
    }

    /**
     * Sets the value of the hasPhysicalDisability property.
     * 
     * @param value
     *     allowed object is
     *     {@link FourValDKRefused }
     *     
     */
    public void setHasPhysicalDisability(FourValDKRefused value) {
        this.hasPhysicalDisability = value;
    }

    /**
     * Gets the value of the receivePhysicalDisabilityServices property.
     * 
     * @return
     *     possible object is
     *     {@link FourValDKRefused }
     *     
     */
    public FourValDKRefused getReceivePhysicalDisabilityServices() {
        return receivePhysicalDisabilityServices;
    }

    /**
     * Sets the value of the receivePhysicalDisabilityServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link FourValDKRefused }
     *     
     */
    public void setReceivePhysicalDisabilityServices(FourValDKRefused value) {
        this.receivePhysicalDisabilityServices = value;
    }

}
