//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for pITCount complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pITCount">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PITCountValue" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="PITCountEffectivePeriod" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}dateRangeCapped" minOccurs="0"/>
 *         &lt;element name="PITCountRecordedDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *       &lt;attribute name="pITHouseholdType" use="required" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}threeValBase" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pITCount", propOrder = {
    "pitCountValue",
    "pitCountEffectivePeriod",
    "pitCountRecordedDate"
})
public class PITCount {

    @XmlElement(name = "PITCountValue", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger pitCountValue;
    @XmlElement(name = "PITCountEffectivePeriod")
    protected DateRangeCapped pitCountEffectivePeriod;
    @XmlElement(name = "PITCountRecordedDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar pitCountRecordedDate;
    @XmlAttribute(name = "pITHouseholdType", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd", required = true)
    protected long pitHouseholdType;

    /**
     * Gets the value of the pitCountValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPITCountValue() {
        return pitCountValue;
    }

    /**
     * Sets the value of the pitCountValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPITCountValue(BigInteger value) {
        this.pitCountValue = value;
    }

    /**
     * Gets the value of the pitCountEffectivePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link DateRangeCapped }
     *     
     */
    public DateRangeCapped getPITCountEffectivePeriod() {
        return pitCountEffectivePeriod;
    }

    /**
     * Sets the value of the pitCountEffectivePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRangeCapped }
     *     
     */
    public void setPITCountEffectivePeriod(DateRangeCapped value) {
        this.pitCountEffectivePeriod = value;
    }

    /**
     * Gets the value of the pitCountRecordedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPITCountRecordedDate() {
        return pitCountRecordedDate;
    }

    /**
     * Sets the value of the pitCountRecordedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPITCountRecordedDate(XMLGregorianCalendar value) {
        this.pitCountRecordedDate = value;
    }

    /**
     * Gets the value of the pitHouseholdType property.
     * 
     */
    public long getPITHouseholdType() {
        return pitHouseholdType;
    }

    /**
     * Sets the value of the pitHouseholdType property.
     * 
     */
    public void setPITHouseholdType(long value) {
        this.pitHouseholdType = value;
    }

}
