//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Based on 1/15/2010 "2010 Housing Inventory and 2010 Point-in-Time Homeless Persons Counts Data Collection Guidance"	
 * 
 * <p>Java class for pITCountSet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pITCountSet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PITCountSetID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}iDIndex"/>
 *         &lt;element name="HUDWaiverReceived" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}twoValBase" minOccurs="0"/>
 *         &lt;element name="HUDWaiverDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="HUDWaiverEffectivePeriod" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}dateRangeOpen" minOccurs="0"/>
 *         &lt;element name="LastPITShelteredCountDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="LastPITUnshelteredCountDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PITCounts" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}pITCounts" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pITCountSet", propOrder = {
    "pitCountSetID",
    "hudWaiverReceived",
    "hudWaiverDate",
    "hudWaiverEffectivePeriod",
    "lastPITShelteredCountDate",
    "lastPITUnshelteredCountDate",
    "pitCounts"
})
public class PITCountSet {

    @XmlElement(name = "PITCountSetID", required = true)
    protected IDIndex pitCountSetID;
    @XmlElement(name = "HUDWaiverReceived")
    protected Long hudWaiverReceived;
    @XmlElement(name = "HUDWaiverDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar hudWaiverDate;
    @XmlElement(name = "HUDWaiverEffectivePeriod")
    protected DateRangeOpen hudWaiverEffectivePeriod;
    @XmlElement(name = "LastPITShelteredCountDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastPITShelteredCountDate;
    @XmlElement(name = "LastPITUnshelteredCountDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastPITUnshelteredCountDate;
    @XmlElement(name = "PITCounts")
    protected PITCounts pitCounts;

    /**
     * Gets the value of the pitCountSetID property.
     * 
     * @return
     *     possible object is
     *     {@link IDIndex }
     *     
     */
    public IDIndex getPITCountSetID() {
        return pitCountSetID;
    }

    /**
     * Sets the value of the pitCountSetID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDIndex }
     *     
     */
    public void setPITCountSetID(IDIndex value) {
        this.pitCountSetID = value;
    }

    /**
     * Gets the value of the hudWaiverReceived property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getHUDWaiverReceived() {
        return hudWaiverReceived;
    }

    /**
     * Sets the value of the hudWaiverReceived property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHUDWaiverReceived(Long value) {
        this.hudWaiverReceived = value;
    }

    /**
     * Gets the value of the hudWaiverDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getHUDWaiverDate() {
        return hudWaiverDate;
    }

    /**
     * Sets the value of the hudWaiverDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setHUDWaiverDate(XMLGregorianCalendar value) {
        this.hudWaiverDate = value;
    }

    /**
     * Gets the value of the hudWaiverEffectivePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link DateRangeOpen }
     *     
     */
    public DateRangeOpen getHUDWaiverEffectivePeriod() {
        return hudWaiverEffectivePeriod;
    }

    /**
     * Sets the value of the hudWaiverEffectivePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRangeOpen }
     *     
     */
    public void setHUDWaiverEffectivePeriod(DateRangeOpen value) {
        this.hudWaiverEffectivePeriod = value;
    }

    /**
     * Gets the value of the lastPITShelteredCountDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastPITShelteredCountDate() {
        return lastPITShelteredCountDate;
    }

    /**
     * Sets the value of the lastPITShelteredCountDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastPITShelteredCountDate(XMLGregorianCalendar value) {
        this.lastPITShelteredCountDate = value;
    }

    /**
     * Gets the value of the lastPITUnshelteredCountDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastPITUnshelteredCountDate() {
        return lastPITUnshelteredCountDate;
    }

    /**
     * Sets the value of the lastPITUnshelteredCountDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastPITUnshelteredCountDate(XMLGregorianCalendar value) {
        this.lastPITUnshelteredCountDate = value;
    }

    /**
     * Gets the value of the pitCounts property.
     * 
     * @return
     *     possible object is
     *     {@link PITCounts }
     *     
     */
    public PITCounts getPITCounts() {
        return pitCounts;
    }

    /**
     * Sets the value of the pitCounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link PITCounts }
     *     
     */
    public void setPITCounts(PITCounts value) {
        this.pitCounts = value;
    }

}
