//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for priorResidence complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="priorResidence">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PriorResidenceID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}iDIndex"/>
 *         &lt;element name="PriorResidenceCode" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}residence" minOccurs="0"/>
 *         &lt;element name="PriorResidenceOther" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}string50" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "priorResidence", propOrder = {
    "priorResidenceID",
    "priorResidenceCode",
    "priorResidenceOther"
})
public class PriorResidence {

    @XmlElement(name = "PriorResidenceID", required = true)
    protected IDIndex priorResidenceID;
    @XmlElement(name = "PriorResidenceCode")
    protected Residence priorResidenceCode;
    @XmlElement(name = "PriorResidenceOther")
    protected String50 priorResidenceOther;

    /**
     * Gets the value of the priorResidenceID property.
     * 
     * @return
     *     possible object is
     *     {@link IDIndex }
     *     
     */
    public IDIndex getPriorResidenceID() {
        return priorResidenceID;
    }

    /**
     * Sets the value of the priorResidenceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDIndex }
     *     
     */
    public void setPriorResidenceID(IDIndex value) {
        this.priorResidenceID = value;
    }

    /**
     * Gets the value of the priorResidenceCode property.
     * 
     * @return
     *     possible object is
     *     {@link Residence }
     *     
     */
    public Residence getPriorResidenceCode() {
        return priorResidenceCode;
    }

    /**
     * Sets the value of the priorResidenceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Residence }
     *     
     */
    public void setPriorResidenceCode(Residence value) {
        this.priorResidenceCode = value;
    }

    /**
     * Gets the value of the priorResidenceOther property.
     * 
     * @return
     *     possible object is
     *     {@link String50 }
     *     
     */
    public String50 getPriorResidenceOther() {
        return priorResidenceOther;
    }

    /**
     * Sets the value of the priorResidenceOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String50 }
     *     
     */
    public void setPriorResidenceOther(String50 value) {
        this.priorResidenceOther = value;
    }

}
