//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for reasonForLeaving complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="reasonForLeaving">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReasonForLeavingID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}iDIndex"/>
 *         &lt;element name="ReasonForLeaving" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}elevenVal" minOccurs="0"/>
 *         &lt;element name="ReasonForLeavingOther" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}string50" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reasonForLeaving", propOrder = {
    "reasonForLeavingID",
    "reasonForLeaving",
    "reasonForLeavingOther"
})
public class ReasonForLeaving {

    @XmlElement(name = "ReasonForLeavingID", required = true)
    protected IDIndex reasonForLeavingID;
    @XmlElement(name = "ReasonForLeaving")
    protected ElevenVal reasonForLeaving;
    @XmlElement(name = "ReasonForLeavingOther")
    protected String50 reasonForLeavingOther;

    /**
     * Gets the value of the reasonForLeavingID property.
     * 
     * @return
     *     possible object is
     *     {@link IDIndex }
     *     
     */
    public IDIndex getReasonForLeavingID() {
        return reasonForLeavingID;
    }

    /**
     * Sets the value of the reasonForLeavingID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDIndex }
     *     
     */
    public void setReasonForLeavingID(IDIndex value) {
        this.reasonForLeavingID = value;
    }

    /**
     * Gets the value of the reasonForLeaving property.
     * 
     * @return
     *     possible object is
     *     {@link ElevenVal }
     *     
     */
    public ElevenVal getReasonForLeaving() {
        return reasonForLeaving;
    }

    /**
     * Sets the value of the reasonForLeaving property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElevenVal }
     *     
     */
    public void setReasonForLeaving(ElevenVal value) {
        this.reasonForLeaving = value;
    }

    /**
     * Gets the value of the reasonForLeavingOther property.
     * 
     * @return
     *     possible object is
     *     {@link String50 }
     *     
     */
    public String50 getReasonForLeavingOther() {
        return reasonForLeavingOther;
    }

    /**
     * Sets the value of the reasonForLeavingOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String50 }
     *     
     */
    public void setReasonForLeavingOther(String50 value) {
        this.reasonForLeavingOther = value;
    }

}
