//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for releaseOfInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="releaseOfInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReleaseOfInformationID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}iDIndex"/>
 *         &lt;element name="SiteServiceID" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="Documentation" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}fourVal"/>
 *         &lt;element name="EffectivePeriod" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}dateRangeOpen"/>
 *         &lt;element name="ReleaseGranted" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}twoVal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "releaseOfInformation", propOrder = {
    "releaseOfInformationID",
    "siteServiceID",
    "documentation",
    "effectivePeriod",
    "releaseGranted"
})
public class ReleaseOfInformation {

    @XmlElement(name = "ReleaseOfInformationID", required = true)
    protected IDIndex releaseOfInformationID;
    @XmlElement(name = "SiteServiceID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger siteServiceID;
    @XmlElement(name = "Documentation", required = true)
    protected FourVal documentation;
    @XmlElement(name = "EffectivePeriod", required = true)
    protected DateRangeOpen effectivePeriod;
    @XmlElement(name = "ReleaseGranted", required = true)
    protected TwoVal releaseGranted;

    /**
     * Gets the value of the releaseOfInformationID property.
     * 
     * @return
     *     possible object is
     *     {@link IDIndex }
     *     
     */
    public IDIndex getReleaseOfInformationID() {
        return releaseOfInformationID;
    }

    /**
     * Sets the value of the releaseOfInformationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDIndex }
     *     
     */
    public void setReleaseOfInformationID(IDIndex value) {
        this.releaseOfInformationID = value;
    }

    /**
     * Gets the value of the siteServiceID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSiteServiceID() {
        return siteServiceID;
    }

    /**
     * Sets the value of the siteServiceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSiteServiceID(BigInteger value) {
        this.siteServiceID = value;
    }

    /**
     * Gets the value of the documentation property.
     * 
     * @return
     *     possible object is
     *     {@link FourVal }
     *     
     */
    public FourVal getDocumentation() {
        return documentation;
    }

    /**
     * Sets the value of the documentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FourVal }
     *     
     */
    public void setDocumentation(FourVal value) {
        this.documentation = value;
    }

    /**
     * Gets the value of the effectivePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link DateRangeOpen }
     *     
     */
    public DateRangeOpen getEffectivePeriod() {
        return effectivePeriod;
    }

    /**
     * Sets the value of the effectivePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRangeOpen }
     *     
     */
    public void setEffectivePeriod(DateRangeOpen value) {
        this.effectivePeriod = value;
    }

    /**
     * Gets the value of the releaseGranted property.
     * 
     * @return
     *     possible object is
     *     {@link TwoVal }
     *     
     */
    public TwoVal getReleaseGranted() {
        return releaseGranted;
    }

    /**
     * Sets the value of the releaseGranted property.
     * 
     * @param value
     *     allowed object is
     *     {@link TwoVal }
     *     
     */
    public void setReleaseGranted(TwoVal value) {
        this.releaseGranted = value;
    }

}
