//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for serviceEvent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="serviceEvent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ServiceEventID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}iDIndex"/>
 *         &lt;element name="SiteServiceID" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="HouseholdID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}id" minOccurs="0"/>
 *         &lt;element name="FundingSources" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}fundingSourcesServiceEvent" minOccurs="0"/>
 *         &lt;element name="IsReferral" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}twoValBase" minOccurs="0"/>
 *         &lt;element name="QuantityOfServiceEvent" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="QuantityOfServiceEventUnit" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}unit" minOccurs="0"/>
 *         &lt;element name="ServiceEventAIRSCode" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}string50Base" minOccurs="0"/>
 *         &lt;element name="ServiceEventEffectivePeriod" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}dateRangeOpen" minOccurs="0"/>
 *         &lt;element name="ServiceEventProvisionDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ServiceEventRecordedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ServiceEventNotes" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}notes" minOccurs="0"/>
 *         &lt;element name="ServiceEventIndFam" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}twoValBase" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="HMISServiceEventCode" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}hMISServiceEvent"/>
 *           &lt;element name="HPRPFinancialAssistanceServiceEventCode" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}sixValBase" minOccurs="0"/>
 *           &lt;element name="HPRPRelocationStabilizationServiceEventCode" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}fiveValBase"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "serviceEvent", propOrder = {
    "serviceEventID",
    "siteServiceID",
    "householdID",
    "fundingSources",
    "isReferral",
    "quantityOfServiceEvent",
    "quantityOfServiceEventUnit",
    "serviceEventAIRSCode",
    "serviceEventEffectivePeriod",
    "serviceEventProvisionDate",
    "serviceEventRecordedDate",
    "serviceEventNotes",
    "serviceEventIndFam",
    "hmisServiceEventCode",
    "hprpFinancialAssistanceServiceEventCode",
    "hprpRelocationStabilizationServiceEventCode"
})
public class ServiceEvent {

    @XmlElement(name = "ServiceEventID", required = true)
    protected IDIndex serviceEventID;
    @XmlElement(name = "SiteServiceID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger siteServiceID;
    @XmlElement(name = "HouseholdID")
    protected Id householdID;
    @XmlElement(name = "FundingSources")
    protected FundingSourcesServiceEvent fundingSources;
    @XmlElement(name = "IsReferral")
    protected Long isReferral;
    @XmlElement(name = "QuantityOfServiceEvent")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger quantityOfServiceEvent;
    @XmlElement(name = "QuantityOfServiceEventUnit")
    protected Unit quantityOfServiceEventUnit;
    @XmlElement(name = "ServiceEventAIRSCode")
    protected String serviceEventAIRSCode;
    @XmlElement(name = "ServiceEventEffectivePeriod")
    protected DateRangeOpen serviceEventEffectivePeriod;
    @XmlElement(name = "ServiceEventProvisionDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar serviceEventProvisionDate;
    @XmlElement(name = "ServiceEventRecordedDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar serviceEventRecordedDate;
    @XmlElement(name = "ServiceEventNotes")
    protected Notes serviceEventNotes;
    @XmlElement(name = "ServiceEventIndFam")
    protected Long serviceEventIndFam;
    @XmlElement(name = "HMISServiceEventCode")
    protected HMISServiceEvent hmisServiceEventCode;
    @XmlElement(name = "HPRPFinancialAssistanceServiceEventCode")
    protected Long hprpFinancialAssistanceServiceEventCode;
    @XmlElement(name = "HPRPRelocationStabilizationServiceEventCode")
    protected Long hprpRelocationStabilizationServiceEventCode;

    /**
     * Gets the value of the serviceEventID property.
     * 
     * @return
     *     possible object is
     *     {@link IDIndex }
     *     
     */
    public IDIndex getServiceEventID() {
        return serviceEventID;
    }

    /**
     * Sets the value of the serviceEventID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDIndex }
     *     
     */
    public void setServiceEventID(IDIndex value) {
        this.serviceEventID = value;
    }

    /**
     * Gets the value of the siteServiceID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSiteServiceID() {
        return siteServiceID;
    }

    /**
     * Sets the value of the siteServiceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSiteServiceID(BigInteger value) {
        this.siteServiceID = value;
    }

    /**
     * Gets the value of the householdID property.
     * 
     * @return
     *     possible object is
     *     {@link Id }
     *     
     */
    public Id getHouseholdID() {
        return householdID;
    }

    /**
     * Sets the value of the householdID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id }
     *     
     */
    public void setHouseholdID(Id value) {
        this.householdID = value;
    }

    /**
     * Gets the value of the fundingSources property.
     * 
     * @return
     *     possible object is
     *     {@link FundingSourcesServiceEvent }
     *     
     */
    public FundingSourcesServiceEvent getFundingSources() {
        return fundingSources;
    }

    /**
     * Sets the value of the fundingSources property.
     * 
     * @param value
     *     allowed object is
     *     {@link FundingSourcesServiceEvent }
     *     
     */
    public void setFundingSources(FundingSourcesServiceEvent value) {
        this.fundingSources = value;
    }

    /**
     * Gets the value of the isReferral property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIsReferral() {
        return isReferral;
    }

    /**
     * Sets the value of the isReferral property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIsReferral(Long value) {
        this.isReferral = value;
    }

    /**
     * Gets the value of the quantityOfServiceEvent property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQuantityOfServiceEvent() {
        return quantityOfServiceEvent;
    }

    /**
     * Sets the value of the quantityOfServiceEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setQuantityOfServiceEvent(BigInteger value) {
        this.quantityOfServiceEvent = value;
    }

    /**
     * Gets the value of the quantityOfServiceEventUnit property.
     * 
     * @return
     *     possible object is
     *     {@link Unit }
     *     
     */
    public Unit getQuantityOfServiceEventUnit() {
        return quantityOfServiceEventUnit;
    }

    /**
     * Sets the value of the quantityOfServiceEventUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Unit }
     *     
     */
    public void setQuantityOfServiceEventUnit(Unit value) {
        this.quantityOfServiceEventUnit = value;
    }

    /**
     * Gets the value of the serviceEventAIRSCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceEventAIRSCode() {
        return serviceEventAIRSCode;
    }

    /**
     * Sets the value of the serviceEventAIRSCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceEventAIRSCode(String value) {
        this.serviceEventAIRSCode = value;
    }

    /**
     * Gets the value of the serviceEventEffectivePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link DateRangeOpen }
     *     
     */
    public DateRangeOpen getServiceEventEffectivePeriod() {
        return serviceEventEffectivePeriod;
    }

    /**
     * Sets the value of the serviceEventEffectivePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRangeOpen }
     *     
     */
    public void setServiceEventEffectivePeriod(DateRangeOpen value) {
        this.serviceEventEffectivePeriod = value;
    }

    /**
     * Gets the value of the serviceEventProvisionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getServiceEventProvisionDate() {
        return serviceEventProvisionDate;
    }

    /**
     * Sets the value of the serviceEventProvisionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setServiceEventProvisionDate(XMLGregorianCalendar value) {
        this.serviceEventProvisionDate = value;
    }

    /**
     * Gets the value of the serviceEventRecordedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getServiceEventRecordedDate() {
        return serviceEventRecordedDate;
    }

    /**
     * Sets the value of the serviceEventRecordedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setServiceEventRecordedDate(XMLGregorianCalendar value) {
        this.serviceEventRecordedDate = value;
    }

    /**
     * Gets the value of the serviceEventNotes property.
     * 
     * @return
     *     possible object is
     *     {@link Notes }
     *     
     */
    public Notes getServiceEventNotes() {
        return serviceEventNotes;
    }

    /**
     * Sets the value of the serviceEventNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notes }
     *     
     */
    public void setServiceEventNotes(Notes value) {
        this.serviceEventNotes = value;
    }

    /**
     * Gets the value of the serviceEventIndFam property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getServiceEventIndFam() {
        return serviceEventIndFam;
    }

    /**
     * Sets the value of the serviceEventIndFam property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setServiceEventIndFam(Long value) {
        this.serviceEventIndFam = value;
    }

    /**
     * Gets the value of the hmisServiceEventCode property.
     * 
     * @return
     *     possible object is
     *     {@link HMISServiceEvent }
     *     
     */
    public HMISServiceEvent getHMISServiceEventCode() {
        return hmisServiceEventCode;
    }

    /**
     * Sets the value of the hmisServiceEventCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link HMISServiceEvent }
     *     
     */
    public void setHMISServiceEventCode(HMISServiceEvent value) {
        this.hmisServiceEventCode = value;
    }

    /**
     * Gets the value of the hprpFinancialAssistanceServiceEventCode property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getHPRPFinancialAssistanceServiceEventCode() {
        return hprpFinancialAssistanceServiceEventCode;
    }

    /**
     * Sets the value of the hprpFinancialAssistanceServiceEventCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHPRPFinancialAssistanceServiceEventCode(Long value) {
        this.hprpFinancialAssistanceServiceEventCode = value;
    }

    /**
     * Gets the value of the hprpRelocationStabilizationServiceEventCode property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getHPRPRelocationStabilizationServiceEventCode() {
        return hprpRelocationStabilizationServiceEventCode;
    }

    /**
     * Sets the value of the hprpRelocationStabilizationServiceEventCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHPRPRelocationStabilizationServiceEventCode(Long value) {
        this.hprpRelocationStabilizationServiceEventCode = value;
    }

}
