//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import org.pathways.openciss.info.hmis.schema._3_0.airs_3_0_mod.TService;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for service complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="service">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd}tService">
 *       &lt;sequence>
 *         &lt;element name="COCCode" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}string5Base" minOccurs="0"/>
 *         &lt;element name="Configuration" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}threeValBase" minOccurs="0"/>
 *         &lt;element name="DirectServiceCode" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}twoValBase" minOccurs="0"/>
 *         &lt;element name="FundingSources" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}fundingSourcesService" minOccurs="0"/>
 *         &lt;element name="GranteeIdentifier" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}string10Base" minOccurs="0"/>
 *         &lt;element name="IndividualFamilyCode" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}fourValBase" minOccurs="0"/>
 *         &lt;element name="Inventory" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}inventory" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ResidentialTrackingMethod" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}threeValBase" minOccurs="0"/>
 *         &lt;element name="ServiceType" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}serviceType" minOccurs="0"/>
 *         &lt;element name="ServiceEffectivePeriod" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}dateRangeOpen" minOccurs="0"/>
 *         &lt;element name="ServiceRecordedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="TargetPopulationA" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}elevenValBase" minOccurs="0"/>
 *         &lt;element name="TargetPopulationB" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}fourValBase" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}deleteStampGroup"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "service", propOrder = {
    "cocCode",
    "configuration",
    "directServiceCode",
    "fundingSources",
    "granteeIdentifier",
    "individualFamilyCode",
    "inventory",
    "residentialTrackingMethod",
    "serviceType",
    "serviceEffectivePeriod",
    "serviceRecordedDate",
    "targetPopulationA",
    "targetPopulationB"
})
public class Service
    extends TService
{

    @XmlElement(name = "COCCode")
    protected String cocCode;
    @XmlElement(name = "Configuration")
    protected Long configuration;
    @XmlElement(name = "DirectServiceCode")
    protected Long directServiceCode;
    @XmlElement(name = "FundingSources")
    protected FundingSourcesService fundingSources;
    @XmlElement(name = "GranteeIdentifier")
    protected String granteeIdentifier;
    @XmlElement(name = "IndividualFamilyCode")
    protected Long individualFamilyCode;
    @XmlElement(name = "Inventory")
    protected List<Inventory> inventory;
    @XmlElement(name = "ResidentialTrackingMethod")
    protected Long residentialTrackingMethod;
    @XmlElement(name = "ServiceType")
    protected Long serviceType;
    @XmlElement(name = "ServiceEffectivePeriod")
    protected DateRangeOpen serviceEffectivePeriod;
    @XmlElement(name = "ServiceRecordedDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar serviceRecordedDate;
    @XmlElement(name = "TargetPopulationA")
    protected Long targetPopulationA;
    @XmlElement(name = "TargetPopulationB")
    protected Long targetPopulationB;
    @XmlAttribute(name = "delete", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd")
    protected Long delete;
    @XmlAttribute(name = "deleteOccurredDate", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar deleteOccurredDate;
    @XmlAttribute(name = "deleteEffective", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar deleteEffective;

    /**
     * Gets the value of the cocCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOCCode() {
        return cocCode;
    }

    /**
     * Sets the value of the cocCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOCCode(String value) {
        this.cocCode = value;
    }

    /**
     * Gets the value of the configuration property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setConfiguration(Long value) {
        this.configuration = value;
    }

    /**
     * Gets the value of the directServiceCode property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDirectServiceCode() {
        return directServiceCode;
    }

    /**
     * Sets the value of the directServiceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDirectServiceCode(Long value) {
        this.directServiceCode = value;
    }

    /**
     * Gets the value of the fundingSources property.
     * 
     * @return
     *     possible object is
     *     {@link FundingSourcesService }
     *     
     */
    public FundingSourcesService getFundingSources() {
        return fundingSources;
    }

    /**
     * Sets the value of the fundingSources property.
     * 
     * @param value
     *     allowed object is
     *     {@link FundingSourcesService }
     *     
     */
    public void setFundingSources(FundingSourcesService value) {
        this.fundingSources = value;
    }

    /**
     * Gets the value of the granteeIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGranteeIdentifier() {
        return granteeIdentifier;
    }

    /**
     * Sets the value of the granteeIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGranteeIdentifier(String value) {
        this.granteeIdentifier = value;
    }

    /**
     * Gets the value of the individualFamilyCode property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIndividualFamilyCode() {
        return individualFamilyCode;
    }

    /**
     * Sets the value of the individualFamilyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIndividualFamilyCode(Long value) {
        this.individualFamilyCode = value;
    }

    /**
     * Gets the value of the inventory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inventory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInventory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Inventory }
     * 
     * 
     */
    public List<Inventory> getInventory() {
        if (inventory == null) {
            inventory = new ArrayList<Inventory>();
        }
        return this.inventory;
    }

    /**
     * Gets the value of the residentialTrackingMethod property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getResidentialTrackingMethod() {
        return residentialTrackingMethod;
    }

    /**
     * Sets the value of the residentialTrackingMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setResidentialTrackingMethod(Long value) {
        this.residentialTrackingMethod = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setServiceType(Long value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the serviceEffectivePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link DateRangeOpen }
     *     
     */
    public DateRangeOpen getServiceEffectivePeriod() {
        return serviceEffectivePeriod;
    }

    /**
     * Sets the value of the serviceEffectivePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRangeOpen }
     *     
     */
    public void setServiceEffectivePeriod(DateRangeOpen value) {
        this.serviceEffectivePeriod = value;
    }

    /**
     * Gets the value of the serviceRecordedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getServiceRecordedDate() {
        return serviceRecordedDate;
    }

    /**
     * Sets the value of the serviceRecordedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setServiceRecordedDate(XMLGregorianCalendar value) {
        this.serviceRecordedDate = value;
    }

    /**
     * Gets the value of the targetPopulationA property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTargetPopulationA() {
        return targetPopulationA;
    }

    /**
     * Sets the value of the targetPopulationA property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTargetPopulationA(Long value) {
        this.targetPopulationA = value;
    }

    /**
     * Gets the value of the targetPopulationB property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTargetPopulationB() {
        return targetPopulationB;
    }

    /**
     * Sets the value of the targetPopulationB property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTargetPopulationB(Long value) {
        this.targetPopulationB = value;
    }

    /**
     * Gets the value of the delete property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getDelete() {
        if (delete == null) {
            return  1L;
        } else {
            return delete;
        }
    }

    /**
     * Sets the value of the delete property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDelete(Long value) {
        this.delete = value;
    }

    /**
     * Gets the value of the deleteOccurredDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeleteOccurredDate() {
        return deleteOccurredDate;
    }

    /**
     * Sets the value of the deleteOccurredDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeleteOccurredDate(XMLGregorianCalendar value) {
        this.deleteOccurredDate = value;
    }

    /**
     * Gets the value of the deleteEffective property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeleteEffective() {
        return deleteEffective;
    }

    /**
     * Sets the value of the deleteEffective property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeleteEffective(XMLGregorianCalendar value) {
        this.deleteEffective = value;
    }

}
