//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for siteServiceParticipation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="siteServiceParticipation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SiteServiceParticipationID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}iDIndex"/>
 *         &lt;element name="SiteServiceID" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="HouseholdID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}id" minOccurs="0"/>
 *         &lt;element name="Need" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}need" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ParticipationDates" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}dateRangeOpen"/>
 *         &lt;element name="PersonHistorical" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}personHistorical" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ReasonsForLeaving" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}reasonForLeaving" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ServiceEvent" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}serviceEvent" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "siteServiceParticipation", propOrder = {
    "siteServiceParticipationID",
    "siteServiceID",
    "householdID",
    "need",
    "participationDates",
    "personHistorical",
    "reasonsForLeaving",
    "serviceEvent"
})
public class SiteServiceParticipation {

    @XmlElement(name = "SiteServiceParticipationID", required = true)
    protected IDIndex siteServiceParticipationID;
    @XmlElement(name = "SiteServiceID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger siteServiceID;
    @XmlElement(name = "HouseholdID")
    protected Id householdID;
    @XmlElement(name = "Need")
    protected List<Need> need;
    @XmlElement(name = "ParticipationDates", required = true)
    protected DateRangeOpen participationDates;
    @XmlElement(name = "PersonHistorical")
    protected List<PersonHistorical> personHistorical;
    @XmlElement(name = "ReasonsForLeaving")
    protected List<ReasonForLeaving> reasonsForLeaving;
    @XmlElement(name = "ServiceEvent")
    protected List<ServiceEvent> serviceEvent;

    /**
     * Gets the value of the siteServiceParticipationID property.
     * 
     * @return
     *     possible object is
     *     {@link IDIndex }
     *     
     */
    public IDIndex getSiteServiceParticipationID() {
        return siteServiceParticipationID;
    }

    /**
     * Sets the value of the siteServiceParticipationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDIndex }
     *     
     */
    public void setSiteServiceParticipationID(IDIndex value) {
        this.siteServiceParticipationID = value;
    }

    /**
     * Gets the value of the siteServiceID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSiteServiceID() {
        return siteServiceID;
    }

    /**
     * Sets the value of the siteServiceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSiteServiceID(BigInteger value) {
        this.siteServiceID = value;
    }

    /**
     * Gets the value of the householdID property.
     * 
     * @return
     *     possible object is
     *     {@link Id }
     *     
     */
    public Id getHouseholdID() {
        return householdID;
    }

    /**
     * Sets the value of the householdID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id }
     *     
     */
    public void setHouseholdID(Id value) {
        this.householdID = value;
    }

    /**
     * Gets the value of the need property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the need property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNeed().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Need }
     * 
     * 
     */
    public List<Need> getNeed() {
        if (need == null) {
            need = new ArrayList<Need>();
        }
        return this.need;
    }

    /**
     * Gets the value of the participationDates property.
     * 
     * @return
     *     possible object is
     *     {@link DateRangeOpen }
     *     
     */
    public DateRangeOpen getParticipationDates() {
        return participationDates;
    }

    /**
     * Sets the value of the participationDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRangeOpen }
     *     
     */
    public void setParticipationDates(DateRangeOpen value) {
        this.participationDates = value;
    }

    /**
     * Gets the value of the personHistorical property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personHistorical property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonHistorical().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonHistorical }
     * 
     * 
     */
    public List<PersonHistorical> getPersonHistorical() {
        if (personHistorical == null) {
            personHistorical = new ArrayList<PersonHistorical>();
        }
        return this.personHistorical;
    }

    /**
     * Gets the value of the reasonsForLeaving property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reasonsForLeaving property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReasonsForLeaving().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReasonForLeaving }
     * 
     * 
     */
    public List<ReasonForLeaving> getReasonsForLeaving() {
        if (reasonsForLeaving == null) {
            reasonsForLeaving = new ArrayList<ReasonForLeaving>();
        }
        return this.reasonsForLeaving;
    }

    /**
     * Gets the value of the serviceEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviceEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceEvent }
     * 
     * 
     */
    public List<ServiceEvent> getServiceEvent() {
        if (serviceEvent == null) {
            serviceEvent = new ArrayList<ServiceEvent>();
        }
        return this.serviceEvent;
    }

}
