//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import org.pathways.openciss.info.hmis.schema._3_0.airs_3_0_mod.TSiteService;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for siteService complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="siteService">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd}tSiteService">
 *       &lt;sequence>
 *         &lt;element name="ServiceID" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="SiteID" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="GeographicCode" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}geographicCode" minOccurs="0"/>
 *         &lt;element name="HMISAsset" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}hMISAsset" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="HousingType" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}sevenVal" minOccurs="0"/>
 *         &lt;element name="Inventory" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}inventory" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Principal" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}twoValBase" minOccurs="0"/>
 *         &lt;element name="PITCountSet" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}pITCountSet" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SiteServiceEffectivePeriod" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}dateRangeOpen" minOccurs="0"/>
 *         &lt;element name="SiteServiceRecordedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="SiteServiceType" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}threeValBase" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}deleteStampGroup"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "siteService", propOrder = {
    "serviceID",
    "siteID",
    "geographicCode",
    "hmisAsset",
    "housingType",
    "inventory",
    "principal",
    "pitCountSet",
    "siteServiceEffectivePeriod",
    "siteServiceRecordedDate",
    "siteServiceType"
})
public class SiteService
    extends TSiteService
{

    @XmlElement(name = "ServiceID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger serviceID;
    @XmlElement(name = "SiteID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger siteID;
    @XmlElement(name = "GeographicCode")
    protected GeographicCode geographicCode;
    @XmlElement(name = "HMISAsset")
    protected List<HMISAsset> hmisAsset;
    @XmlElement(name = "HousingType")
    protected SevenVal housingType;
    @XmlElement(name = "Inventory")
    protected List<Inventory> inventory;
    @XmlElement(name = "Principal")
    protected Long principal;
    @XmlElement(name = "PITCountSet")
    protected List<PITCountSet> pitCountSet;
    @XmlElement(name = "SiteServiceEffectivePeriod")
    protected DateRangeOpen siteServiceEffectivePeriod;
    @XmlElement(name = "SiteServiceRecordedDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar siteServiceRecordedDate;
    @XmlElement(name = "SiteServiceType")
    protected Long siteServiceType;
    @XmlAttribute(name = "delete", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd")
    protected Long delete;
    @XmlAttribute(name = "deleteOccurredDate", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar deleteOccurredDate;
    @XmlAttribute(name = "deleteEffective", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar deleteEffective;

    /**
     * Gets the value of the serviceID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getServiceID() {
        return serviceID;
    }

    /**
     * Sets the value of the serviceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setServiceID(BigInteger value) {
        this.serviceID = value;
    }

    /**
     * Gets the value of the siteID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSiteID() {
        return siteID;
    }

    /**
     * Sets the value of the siteID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSiteID(BigInteger value) {
        this.siteID = value;
    }

    /**
     * Gets the value of the geographicCode property.
     * 
     * @return
     *     possible object is
     *     {@link GeographicCode }
     *     
     */
    public GeographicCode getGeographicCode() {
        return geographicCode;
    }

    /**
     * Sets the value of the geographicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeographicCode }
     *     
     */
    public void setGeographicCode(GeographicCode value) {
        this.geographicCode = value;
    }

    /**
     * Gets the value of the hmisAsset property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hmisAsset property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHMISAsset().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HMISAsset }
     * 
     * 
     */
    public List<HMISAsset> getHMISAsset() {
        if (hmisAsset == null) {
            hmisAsset = new ArrayList<HMISAsset>();
        }
        return this.hmisAsset;
    }

    /**
     * Gets the value of the housingType property.
     * 
     * @return
     *     possible object is
     *     {@link SevenVal }
     *     
     */
    public SevenVal getHousingType() {
        return housingType;
    }

    /**
     * Sets the value of the housingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SevenVal }
     *     
     */
    public void setHousingType(SevenVal value) {
        this.housingType = value;
    }

    /**
     * Gets the value of the inventory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inventory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInventory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Inventory }
     * 
     * 
     */
    public List<Inventory> getInventory() {
        if (inventory == null) {
            inventory = new ArrayList<Inventory>();
        }
        return this.inventory;
    }

    /**
     * Gets the value of the principal property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPrincipal() {
        return principal;
    }

    /**
     * Sets the value of the principal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPrincipal(Long value) {
        this.principal = value;
    }

    /**
     * Gets the value of the pitCountSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pitCountSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPITCountSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PITCountSet }
     * 
     * 
     */
    public List<PITCountSet> getPITCountSet() {
        if (pitCountSet == null) {
            pitCountSet = new ArrayList<PITCountSet>();
        }
        return this.pitCountSet;
    }

    /**
     * Gets the value of the siteServiceEffectivePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link DateRangeOpen }
     *     
     */
    public DateRangeOpen getSiteServiceEffectivePeriod() {
        return siteServiceEffectivePeriod;
    }

    /**
     * Sets the value of the siteServiceEffectivePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRangeOpen }
     *     
     */
    public void setSiteServiceEffectivePeriod(DateRangeOpen value) {
        this.siteServiceEffectivePeriod = value;
    }

    /**
     * Gets the value of the siteServiceRecordedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSiteServiceRecordedDate() {
        return siteServiceRecordedDate;
    }

    /**
     * Sets the value of the siteServiceRecordedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSiteServiceRecordedDate(XMLGregorianCalendar value) {
        this.siteServiceRecordedDate = value;
    }

    /**
     * Gets the value of the siteServiceType property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSiteServiceType() {
        return siteServiceType;
    }

    /**
     * Sets the value of the siteServiceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSiteServiceType(Long value) {
        this.siteServiceType = value;
    }

    /**
     * Gets the value of the delete property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getDelete() {
        if (delete == null) {
            return  1L;
        } else {
            return delete;
        }
    }

    /**
     * Sets the value of the delete property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDelete(Long value) {
        this.delete = value;
    }

    /**
     * Gets the value of the deleteOccurredDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeleteOccurredDate() {
        return deleteOccurredDate;
    }

    /**
     * Sets the value of the deleteOccurredDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeleteOccurredDate(XMLGregorianCalendar value) {
        this.deleteOccurredDate = value;
    }

    /**
     * Gets the value of the deleteEffective property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeleteEffective() {
        return deleteEffective;
    }

    /**
     * Sets the value of the deleteEffective property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeleteEffective(XMLGregorianCalendar value) {
        this.deleteEffective = value;
    }

}
