//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for sixValDKRefused2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sixValDKRefused2">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.hmis.info/schema/3_0/HUD_HMIS.xsd>sixValDKRefused2Base">
 *       &lt;attGroup ref="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}dateStampGroup"/>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sixValDKRefused2", propOrder = {
    "value"
})
public class SixValDKRefused2 {

    @XmlValue
    protected long value;
    @XmlAttribute(name = "dateCollected", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateCollected;
    @XmlAttribute(name = "dateEffective", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateEffective;
    @XmlAttribute(name = "dataCollectionStage", namespace = "http://www.hmis.info/schema/3_0/HUD_HMIS.xsd")
    protected Long dataCollectionStage;

    /**
     * 
     * 				Applicable to:
     * 				Housing Status
     *     				1 = Literally homeless
     *     				2 = Housed and at imminent risk of losing housing
     *     				3 = Housed and at-risk of losing housing
     *     				4 = Stably housed
     *     				8 = Don’t Know
     *     				9 = Refused
     *     			When Domestic Violence Occurred 
     *     				1= Within the past three months
     *     				2= Three to six months ago
     *     				3= From six to twelve months ago
     *     				4= More than a year ago
     *     				8= Don’t Know
     *     				9= Refused
     * 			
     * 
     */
    public long getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(long value) {
        this.value = value;
    }

    /**
     * Gets the value of the dateCollected property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateCollected() {
        return dateCollected;
    }

    /**
     * Sets the value of the dateCollected property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateCollected(XMLGregorianCalendar value) {
        this.dateCollected = value;
    }

    /**
     * Gets the value of the dateEffective property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateEffective() {
        return dateEffective;
    }

    /**
     * Sets the value of the dateEffective property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateEffective(XMLGregorianCalendar value) {
        this.dateEffective = value;
    }

    /**
     * Gets the value of the dataCollectionStage property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDataCollectionStage() {
        return dataCollectionStage;
    }

    /**
     * Sets the value of the dataCollectionStage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDataCollectionStage(Long value) {
        this.dataCollectionStage = value;
    }

}
