//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.hud_hmis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for warZoneServed complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="warZoneServed">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WarZoneID" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}iDIndex"/>
 *         &lt;element name="MonthsInWarZone" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="ReceivedFire" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}fourValDKRefused" minOccurs="0"/>
 *         &lt;element name="WarZone" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}warZone" minOccurs="0"/>
 *         &lt;element name="WarZoneOther" type="{http://www.hmis.info/schema/3_0/HUD_HMIS.xsd}string50" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "warZoneServed", propOrder = {
    "warZoneID",
    "monthsInWarZone",
    "receivedFire",
    "warZone",
    "warZoneOther"
})
public class WarZoneServed {

    @XmlElement(name = "WarZoneID", required = true)
    protected IDIndex warZoneID;
    @XmlElement(name = "MonthsInWarZone")
    protected NonNegativeInteger monthsInWarZone;
    @XmlElement(name = "ReceivedFire")
    protected FourValDKRefused receivedFire;
    @XmlElement(name = "WarZone")
    protected WarZone warZone;
    @XmlElement(name = "WarZoneOther")
    protected String50 warZoneOther;

    /**
     * Gets the value of the warZoneID property.
     * 
     * @return
     *     possible object is
     *     {@link IDIndex }
     *     
     */
    public IDIndex getWarZoneID() {
        return warZoneID;
    }

    /**
     * Sets the value of the warZoneID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDIndex }
     *     
     */
    public void setWarZoneID(IDIndex value) {
        this.warZoneID = value;
    }

    /**
     * Gets the value of the monthsInWarZone property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeInteger }
     *     
     */
    public NonNegativeInteger getMonthsInWarZone() {
        return monthsInWarZone;
    }

    /**
     * Sets the value of the monthsInWarZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeInteger }
     *     
     */
    public void setMonthsInWarZone(NonNegativeInteger value) {
        this.monthsInWarZone = value;
    }

    /**
     * Gets the value of the receivedFire property.
     * 
     * @return
     *     possible object is
     *     {@link FourValDKRefused }
     *     
     */
    public FourValDKRefused getReceivedFire() {
        return receivedFire;
    }

    /**
     * Sets the value of the receivedFire property.
     * 
     * @param value
     *     allowed object is
     *     {@link FourValDKRefused }
     *     
     */
    public void setReceivedFire(FourValDKRefused value) {
        this.receivedFire = value;
    }

    /**
     * Gets the value of the warZone property.
     * 
     * @return
     *     possible object is
     *     {@link WarZone }
     *     
     */
    public WarZone getWarZone() {
        return warZone;
    }

    /**
     * Sets the value of the warZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link WarZone }
     *     
     */
    public void setWarZone(WarZone value) {
        this.warZone = value;
    }

    /**
     * Gets the value of the warZoneOther property.
     * 
     * @return
     *     possible object is
     *     {@link String50 }
     *     
     */
    public String50 getWarZoneOther() {
        return warZoneOther;
    }

    /**
     * Sets the value of the warZoneOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String50 }
     *     
     */
    public void setWarZoneOther(String50 value) {
        this.warZoneOther = value;
    }

}
