//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.airs_3_0_mod;

import java.math.BigInteger;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the info.hmis.schema._3_0.airs_3_0_mod package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TGeographicAreaServedDescription_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "Description");
    private final static QName _TGeographicAreaServedCounty_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "County");
    private final static QName _TGeographicAreaServedState_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "State");
    private final static QName _TGeographicAreaServedCountry_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "Country");
    private final static QName _TGeographicAreaServedZipCode_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "ZipCode");
    private final static QName _TGeographicAreaServedCity_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "City");
    private final static QName _TGeographicAreaServedCensusTrack_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "CensusTrack");
    private final static QName _TSiteSiteService_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "SiteService");
    private final static QName _TSiteName_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "Name");
    private final static QName _TSitePhysicalAddress_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "PhysicalAddress");
    private final static QName _TSiteEmail_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "Email");
    private final static QName _TSiteSiteDescription_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "SiteDescription");
    private final static QName _TSiteAKA_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "AKA");
    private final static QName _TSiteURL_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "URL");
    private final static QName _TSiteBusServiceAccess_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "BusServiceAccess");
    private final static QName _TSiteTimeOpen_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "TimeOpen");
    private final static QName _TSitePhone_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "Phone");
    private final static QName _TSiteDisabilitiesAccess_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "DisabilitiesAccess");
    private final static QName _TSiteKey_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "Key");
    private final static QName _TSiteOtherAddress_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "OtherAddress");
    private final static QName _TSitePhysicalLocationDescription_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "PhysicalLocationDescription");
    private final static QName _TSiteContact_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "Contact");
    private final static QName _TSiteNoPhysicalAddress_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "NoPhysicalAddress");
    private final static QName _TSiteSpatialLocation_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "SpatialLocation");
    private final static QName _TSiteMailingAddress_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "MailingAddress");
    private final static QName _TSiteCrossStreet_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "CrossStreet");
    private final static QName _TSiteLanguages_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "Languages");
    private final static QName _TDayTo_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "To");
    private final static QName _TDayFrom_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "From");
    private final static QName _TLanguagesNotes_QNAME = new QName("http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", "Notes");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: info.hmis.schema._3_0.airs_3_0_mod
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TService }
     * 
     */
    public TService createTService() {
        return new TService();
    }

    /**
     * Create an instance of {@link TSiteService }
     * 
     */
    public TSiteService createTSiteService() {
        return new TSiteService();
    }

    /**
     * Create an instance of {@link TSeasonal }
     * 
     */
    public TSeasonal createTSeasonal() {
        return new TSeasonal();
    }

    /**
     * Create an instance of {@link TLanguages }
     * 
     */
    public TLanguages createTLanguages() {
        return new TLanguages();
    }

    /**
     * Create an instance of {@link TTimeOpen }
     * 
     */
    public TTimeOpen createTTimeOpen() {
        return new TTimeOpen();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link TAgeRequirements }
     * 
     */
    public TAgeRequirements createTAgeRequirements() {
        return new TAgeRequirements();
    }

    /**
     * Create an instance of {@link TAddress }
     * 
     */
    public TAddress createTAddress() {
        return new TAddress();
    }

    /**
     * Create an instance of {@link TAgency }
     * 
     */
    public TAgency createTAgency() {
        return new TAgency();
    }

    /**
     * Create an instance of {@link TSpatialLocation }
     * 
     */
    public TSpatialLocation createTSpatialLocation() {
        return new TSpatialLocation();
    }

    /**
     * Create an instance of {@link TServiceGroup }
     * 
     */
    public TServiceGroup createTServiceGroup() {
        return new TServiceGroup();
    }

    /**
     * Create an instance of {@link TDocumentsRequired }
     * 
     */
    public TDocumentsRequired createTDocumentsRequired() {
        return new TDocumentsRequired();
    }

    /**
     * Create an instance of {@link TEMail }
     * 
     */
    public TEMail createTEMail() {
        return new TEMail();
    }

    /**
     * Create an instance of {@link TLicenseAccreditation }
     * 
     */
    public TLicenseAccreditation createTLicenseAccreditation() {
        return new TLicenseAccreditation();
    }

    /**
     * Create an instance of {@link TGeographicAreaServed }
     * 
     */
    public TGeographicAreaServed createTGeographicAreaServed() {
        return new TGeographicAreaServed();
    }

    /**
     * Create an instance of {@link TContact }
     * 
     */
    public TContact createTContact() {
        return new TContact();
    }

    /**
     * Create an instance of {@link TNoPhysicalAddress }
     * 
     */
    public TNoPhysicalAddress createTNoPhysicalAddress() {
        return new TNoPhysicalAddress();
    }

    /**
     * Create an instance of {@link TApplicationProcess }
     * 
     */
    public TApplicationProcess createTApplicationProcess() {
        return new TApplicationProcess();
    }

    /**
     * Create an instance of {@link TPhone }
     * 
     */
    public TPhone createTPhone() {
        return new TPhone();
    }

    /**
     * Create an instance of {@link TTaxonomy }
     * 
     */
    public TTaxonomy createTTaxonomy() {
        return new TTaxonomy();
    }

    /**
     * Create an instance of {@link TURL }
     * 
     */
    public TURL createTURL() {
        return new TURL();
    }

    /**
     * Create an instance of {@link TDay }
     * 
     */
    public TDay createTDay() {
        return new TDay();
    }

    /**
     * Create an instance of {@link TAKA }
     * 
     */
    public TAKA createTAKA() {
        return new TAKA();
    }

    /**
     * Create an instance of {@link TResourceInfo }
     * 
     */
    public TResourceInfo createTResourceInfo() {
        return new TResourceInfo();
    }

    /**
     * Create an instance of {@link TSite }
     * 
     */
    public TSite createTSite() {
        return new TSite();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "Description", scope = TGeographicAreaServed.class)
    public JAXBElement<String> createTGeographicAreaServedDescription(String value) {
        return new JAXBElement<String>(_TGeographicAreaServedDescription_QNAME, String.class, TGeographicAreaServed.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "County", scope = TGeographicAreaServed.class)
    public JAXBElement<String> createTGeographicAreaServedCounty(String value) {
        return new JAXBElement<String>(_TGeographicAreaServedCounty_QNAME, String.class, TGeographicAreaServed.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "State", scope = TGeographicAreaServed.class)
    public JAXBElement<String> createTGeographicAreaServedState(String value) {
        return new JAXBElement<String>(_TGeographicAreaServedState_QNAME, String.class, TGeographicAreaServed.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "Country", scope = TGeographicAreaServed.class)
    public JAXBElement<String> createTGeographicAreaServedCountry(String value) {
        return new JAXBElement<String>(_TGeographicAreaServedCountry_QNAME, String.class, TGeographicAreaServed.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "ZipCode", scope = TGeographicAreaServed.class)
    public JAXBElement<String> createTGeographicAreaServedZipCode(String value) {
        return new JAXBElement<String>(_TGeographicAreaServedZipCode_QNAME, String.class, TGeographicAreaServed.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "City", scope = TGeographicAreaServed.class)
    public JAXBElement<String> createTGeographicAreaServedCity(String value) {
        return new JAXBElement<String>(_TGeographicAreaServedCity_QNAME, String.class, TGeographicAreaServed.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "CensusTrack", scope = TGeographicAreaServed.class)
    public JAXBElement<String> createTGeographicAreaServedCensusTrack(String value) {
        return new JAXBElement<String>(_TGeographicAreaServedCensusTrack_QNAME, String.class, TGeographicAreaServed.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TSiteService }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "SiteService", scope = TSite.class)
    public JAXBElement<TSiteService> createTSiteSiteService(TSiteService value) {
        return new JAXBElement<TSiteService>(_TSiteSiteService_QNAME, TSiteService.class, TSite.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "Name", scope = TSite.class)
    public JAXBElement<String> createTSiteName(String value) {
        return new JAXBElement<String>(_TSiteName_QNAME, String.class, TSite.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAddress }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "PhysicalAddress", scope = TSite.class)
    public JAXBElement<TAddress> createTSitePhysicalAddress(TAddress value) {
        return new JAXBElement<TAddress>(_TSitePhysicalAddress_QNAME, TAddress.class, TSite.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TEMail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "Email", scope = TSite.class)
    public JAXBElement<TEMail> createTSiteEmail(TEMail value) {
        return new JAXBElement<TEMail>(_TSiteEmail_QNAME, TEMail.class, TSite.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "SiteDescription", scope = TSite.class)
    public JAXBElement<String> createTSiteSiteDescription(String value) {
        return new JAXBElement<String>(_TSiteSiteDescription_QNAME, String.class, TSite.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAKA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "AKA", scope = TSite.class)
    public JAXBElement<TAKA> createTSiteAKA(TAKA value) {
        return new JAXBElement<TAKA>(_TSiteAKA_QNAME, TAKA.class, TSite.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TURL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "URL", scope = TSite.class)
    public JAXBElement<TURL> createTSiteURL(TURL value) {
        return new JAXBElement<TURL>(_TSiteURL_QNAME, TURL.class, TSite.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "BusServiceAccess", scope = TSite.class)
    public JAXBElement<String> createTSiteBusServiceAccess(String value) {
        return new JAXBElement<String>(_TSiteBusServiceAccess_QNAME, String.class, TSite.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTimeOpen }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "TimeOpen", scope = TSite.class)
    public JAXBElement<TTimeOpen> createTSiteTimeOpen(TTimeOpen value) {
        return new JAXBElement<TTimeOpen>(_TSiteTimeOpen_QNAME, TTimeOpen.class, TSite.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPhone }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "Phone", scope = TSite.class)
    public JAXBElement<TPhone> createTSitePhone(TPhone value) {
        return new JAXBElement<TPhone>(_TSitePhone_QNAME, TPhone.class, TSite.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "DisabilitiesAccess", scope = TSite.class)
    public JAXBElement<String> createTSiteDisabilitiesAccess(String value) {
        return new JAXBElement<String>(_TSiteDisabilitiesAccess_QNAME, String.class, TSite.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "Key", scope = TSite.class)
    public JAXBElement<BigInteger> createTSiteKey(BigInteger value) {
        return new JAXBElement<BigInteger>(_TSiteKey_QNAME, BigInteger.class, TSite.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAddress }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "OtherAddress", scope = TSite.class)
    public JAXBElement<TAddress> createTSiteOtherAddress(TAddress value) {
        return new JAXBElement<TAddress>(_TSiteOtherAddress_QNAME, TAddress.class, TSite.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "PhysicalLocationDescription", scope = TSite.class)
    public JAXBElement<String> createTSitePhysicalLocationDescription(String value) {
        return new JAXBElement<String>(_TSitePhysicalLocationDescription_QNAME, String.class, TSite.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TContact }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "Contact", scope = TSite.class)
    public JAXBElement<TContact> createTSiteContact(TContact value) {
        return new JAXBElement<TContact>(_TSiteContact_QNAME, TContact.class, TSite.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TNoPhysicalAddress }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "NoPhysicalAddress", scope = TSite.class)
    public JAXBElement<TNoPhysicalAddress> createTSiteNoPhysicalAddress(TNoPhysicalAddress value) {
        return new JAXBElement<TNoPhysicalAddress>(_TSiteNoPhysicalAddress_QNAME, TNoPhysicalAddress.class, TSite.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TSpatialLocation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "SpatialLocation", scope = TSite.class)
    public JAXBElement<TSpatialLocation> createTSiteSpatialLocation(TSpatialLocation value) {
        return new JAXBElement<TSpatialLocation>(_TSiteSpatialLocation_QNAME, TSpatialLocation.class, TSite.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAddress }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "MailingAddress", scope = TSite.class)
    public JAXBElement<TAddress> createTSiteMailingAddress(TAddress value) {
        return new JAXBElement<TAddress>(_TSiteMailingAddress_QNAME, TAddress.class, TSite.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "CrossStreet", scope = TSite.class)
    public JAXBElement<String> createTSiteCrossStreet(String value) {
        return new JAXBElement<String>(_TSiteCrossStreet_QNAME, String.class, TSite.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TLanguages }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "Languages", scope = TSite.class)
    public JAXBElement<TLanguages> createTSiteLanguages(TLanguages value) {
        return new JAXBElement<TLanguages>(_TSiteLanguages_QNAME, TLanguages.class, TSite.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "To", scope = TDay.class)
    public JAXBElement<XMLGregorianCalendar> createTDayTo(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TDayTo_QNAME, XMLGregorianCalendar.class, TDay.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "From", scope = TDay.class)
    public JAXBElement<XMLGregorianCalendar> createTDayFrom(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TDayFrom_QNAME, XMLGregorianCalendar.class, TDay.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "Name", scope = TLanguages.class)
    public JAXBElement<String> createTLanguagesName(String value) {
        return new JAXBElement<String>(_TSiteName_QNAME, String.class, TLanguages.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "Notes", scope = TLanguages.class)
    public JAXBElement<String> createTLanguagesNotes(String value) {
        return new JAXBElement<String>(_TLanguagesNotes_QNAME, String.class, TLanguages.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTimeOpen }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", name = "TimeOpen", scope = TLanguages.class)
    public JAXBElement<TTimeOpen> createTLanguagesTimeOpen(TTimeOpen value) {
        return new JAXBElement<TTimeOpen>(_TSiteTimeOpen_QNAME, TTimeOpen.class, TLanguages.class, value);
    }

}
