//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.airs_3_0_mod;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * This can be used for any day of the week
 * 
 * <p>Java class for tDay complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tDay">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="From" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *         &lt;element name="To" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tDay", propOrder = {
    "fromAndTo"
})
public class TDay {

    @XmlElementRefs({
        @XmlElementRef(name = "From", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "To", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class)
    })
    protected List<JAXBElement<XMLGregorianCalendar>> fromAndTo;

    /**
     * Gets the value of the fromAndTo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fromAndTo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFromAndTo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * 
     */
    public List<JAXBElement<XMLGregorianCalendar>> getFromAndTo() {
        if (fromAndTo == null) {
            fromAndTo = new ArrayList<JAXBElement<XMLGregorianCalendar>>();
        }
        return this.fromAndTo;
    }

}
