//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.airs_3_0_mod;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 *  Language spoken and the TimeOpen the language is available
 * 
 * <p>Java class for tLanguages complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tLanguages">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TimeOpen" type="{http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd}tTimeOpen" minOccurs="0"/>
 *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tLanguages", propOrder = {
    "nameAndTimeOpenAndNotes"
})
public class TLanguages {

    @XmlElementRefs({
        @XmlElementRef(name = "Name", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "TimeOpen", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "Notes", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> nameAndTimeOpenAndNotes;

    /**
     * Gets the value of the nameAndTimeOpenAndNotes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameAndTimeOpenAndNotes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameAndTimeOpenAndNotes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TTimeOpen }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getNameAndTimeOpenAndNotes() {
        if (nameAndTimeOpenAndNotes == null) {
            nameAndTimeOpenAndNotes = new ArrayList<JAXBElement<?>>();
        }
        return this.nameAndTimeOpenAndNotes;
    }

}
