//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:35:09 PM EDT 
//


package org.pathways.openciss.info.hmis.schema._3_0.airs_3_0_mod;

import org.pathways.openciss.info.hmis.schema._3_0.hud_hmis.Site;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Sites are physical locations or none physical locations (a website or hotline). Site is used for two purposes. First it is used by Agency to provide the location of the agency Agency.AgencyLocation (Note this type of Site would never have any SiteService children). Second sites are also the location where services are provided. This would be the Agency.Site element (Note this type of Site would have SiteService children
 * 			
 * 
 * <p>Java class for tSite complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSite">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SiteDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AKA" type="{http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd}tAKA" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;sequence>
 *             &lt;element name="PhysicalAddress" type="{http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd}tAddress"/>
 *             &lt;element name="MailingAddress" type="{http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd}tAddress"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="MailingAddress" type="{http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd}tAddress"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="NoPhysicalAddress" type="{http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd}tNoPhysicalAddress"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="OtherAddress" type="{http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd}tAddress" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CrossStreet" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Phone" type="{http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd}tPhone" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="URL" type="{http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd}tURL" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Email" type="{http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd}tEMail" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Contact" type="{http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd}tContact" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TimeOpen" type="{http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd}tTimeOpen" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Languages" type="{http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd}tLanguages" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DisabilitiesAccess" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PhysicalLocationDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BusServiceAccess" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SiteService" type="{http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd}tSiteService" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SpatialLocation" type="{http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd}tSpatialLocation" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="PublicAccessToTransportation" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="YearInc" type="{http://www.w3.org/2001/XMLSchema}gYear" />
 *       &lt;attribute name="AnnualBudgetTotal" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="LegalStatus" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ExcludeFromWebsite" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ExcludeFromDirectory" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSite", propOrder = {
    "content"
})
@XmlSeeAlso({
    Site.class
})
public class TSite {

    @XmlElementRefs({
        @XmlElementRef(name = "Phone", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "Name", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "AKA", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "Languages", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "Email", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "MailingAddress", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "NoPhysicalAddress", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "PhysicalLocationDescription", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "DisabilitiesAccess", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "OtherAddress", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "SpatialLocation", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "URL", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "Contact", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "SiteService", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "SiteDescription", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "BusServiceAccess", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "PhysicalAddress", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "TimeOpen", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "Key", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class),
        @XmlElementRef(name = "CrossStreet", namespace = "http://www.hmis.info/schema/3_0/AIRS_3_0_mod.xsd", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> content;
    @XmlAttribute(name = "PublicAccessToTransportation")
    protected Boolean publicAccessToTransportation;
    @XmlAttribute(name = "YearInc")
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar yearInc;
    @XmlAttribute(name = "AnnualBudgetTotal")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger annualBudgetTotal;
    @XmlAttribute(name = "LegalStatus")
    protected String legalStatus;
    @XmlAttribute(name = "ExcludeFromWebsite")
    protected Boolean excludeFromWebsite;
    @XmlAttribute(name = "ExcludeFromDirectory")
    protected Boolean excludeFromDirectory;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "MailingAddress" is used by two different parts of a schema. See: 
     * line 368 of http://xsd.alexandriaconsulting.com/repos/tags/HUD_HMIS_XML/HUD_HMIS_XML_3.0-final-server-move-interim/AIRS_3_0_mod.xsd
     * line 365 of http://xsd.alexandriaconsulting.com/repos/tags/HUD_HMIS_XML/HUD_HMIS_XML_3.0-final-server-move-interim/AIRS_3_0_mod.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link TPhone }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TAKA }{@code >}
     * {@link JAXBElement }{@code <}{@link TAddress }{@code >}
     * {@link JAXBElement }{@code <}{@link TEMail }{@code >}
     * {@link JAXBElement }{@code <}{@link TLanguages }{@code >}
     * {@link JAXBElement }{@code <}{@link TNoPhysicalAddress }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TAddress }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TSpatialLocation }{@code >}
     * {@link JAXBElement }{@code <}{@link TURL }{@code >}
     * {@link JAXBElement }{@code <}{@link TContact }{@code >}
     * {@link JAXBElement }{@code <}{@link TSiteService }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TAddress }{@code >}
     * {@link JAXBElement }{@code <}{@link TTimeOpen }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<?>>();
        }
        return this.content;
    }

    /**
     * Gets the value of the publicAccessToTransportation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPublicAccessToTransportation() {
        return publicAccessToTransportation;
    }

    /**
     * Sets the value of the publicAccessToTransportation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPublicAccessToTransportation(Boolean value) {
        this.publicAccessToTransportation = value;
    }

    /**
     * Gets the value of the yearInc property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getYearInc() {
        return yearInc;
    }

    /**
     * Sets the value of the yearInc property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setYearInc(XMLGregorianCalendar value) {
        this.yearInc = value;
    }

    /**
     * Gets the value of the annualBudgetTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAnnualBudgetTotal() {
        return annualBudgetTotal;
    }

    /**
     * Sets the value of the annualBudgetTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAnnualBudgetTotal(BigInteger value) {
        this.annualBudgetTotal = value;
    }

    /**
     * Gets the value of the legalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalStatus() {
        return legalStatus;
    }

    /**
     * Sets the value of the legalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalStatus(String value) {
        this.legalStatus = value;
    }

    /**
     * Gets the value of the excludeFromWebsite property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExcludeFromWebsite() {
        return excludeFromWebsite;
    }

    /**
     * Sets the value of the excludeFromWebsite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExcludeFromWebsite(Boolean value) {
        this.excludeFromWebsite = value;
    }

    /**
     * Gets the value of the excludeFromDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExcludeFromDirectory() {
        return excludeFromDirectory;
    }

    /**
     * Sets the value of the excludeFromDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExcludeFromDirectory(Boolean value) {
        this.excludeFromDirectory = value;
    }

}
